fatih/vim-go

- autoload/go/tool.vim
This fixes two existing problems:
1.) If `ShowErrors` was run with the quickfix list already populated it would not update the quickfix list if the new output contained a fatal error. e.g. test is fixed, new run results in fatal error, the now-fixed test is still shown in the quickfix list.
2.) It shows stacktraces without the context of the `fatal error`. Before this changed, `ShowErrors` parsed stacktraces (by accident, I assume) and added them to the quickfix list. But without the `fatal
error:` line, it seemed like these stacktraces belonged to a failing test.
This change adds parsing of "fatal error" lines to `ShowErrors`. It checks if a line contains `fatal error:` and if so, it handles the line like a error and adds it to the quickfix list.
The result is that now fatal errors are …
> Parse and add 'fatal errors' to quickfix list

- autoload/go/tool.vim
https://github.com/fatih/vim-go/issues/281
To reproduce the problem in following code:
put cursor on "yaml.Unmarshal", and run `:GoDoc`
```
package main
import (
"io/ioutil"
"gopkg.in/yaml.v2"
)
type config struct {
}
func test() {
if content, err := ioutil.ReadFile("nothing"); err == nil {
c := config{}
err = yaml.Unmarshal(content, &c)
}
}
```
> [Bugfix]GoDoc can not found correct package path when package name has ext

- doc/vim-go.txt
It looks like the docs aren't quite right in https://github.com/fatih/vim-go/pull/272. They show `am`/`im` when the implementation is `af`/`if`. I'm somewhat awful at vimscript so maybe I'm missing something, but only the `f` variant works for me in vim.
> Update docs for function text objects.

- autoload/go/tool.vim
When package with "import path" e.g. `"github.com/bitly/go-simplejson"` is accessible by default with other name (in this case `simplejson`),
GoDoc cannot find this because it cannot dereference "package name" to "import path" because of how go#tool#Imports creates mapping between "package_name" and "import path".
this merge tries to infer real "package name" that if GoDoc is placed on  eg. simplejson.NewJson which is located in "github.com/bitly/go-simplejson" - it correctly finds out the correct path
example of non-working code, before path
```go
import "github.com/bitly/go-simplejson"
func main(){
json, err := simplejson.NewJson()
}
```
I am aware that this is problem with library that not sticks with convention of giving the same name to package and last folder in import path - but it …
> fix GoDoc if package name differs from import path

- autoload/go/complete.vim
- autoload/go/vimproc.vim
On windows, when call the system() function, a console window will be showed up, which will effect the user exprience terribly.
for example, when the auto-complete was enabled every single time a key pressed a console will interrupt the auto-comple window.
It's a nightmare :(
With the help of vimproc, that nightmare is gone. :)
> Add vimproc support for vim-go.

- indent/go.vim
I'm using vim-sleuth[1] from tpope to automatically detect indent
settings for files that I edit. The latest version sets 'shiftwidth' to
zero for files that are detected to be indented only with hard tabs, so
that the value of 'tabstop' is used instead of 'shiftwidth'. This
change[2] was done to allow people setting 'tabstop' to their preferred
value, and to have 'shiftwidth' automatically follow.
The vim documentation about 'shiftwidth' states:
When zero the 'ts' value will be used.  Use the shiftwidth()
function to get the effective shiftwidth value.
Therefore this commit changes using 'sw' directly and instead calls
shiftwidth().
[1] https://github.com/tpope/vim-sleuth
[2] https://github.com/tpope/vim-sleuth/commit/b6b4c3b237678f1214ea2eca0e3e50eaafb30e3a
> Use shiftwidth() instead of '&shiftwidth'

- indent/go.vim
Not all Vim versions have shiftwidth function available to be used, so
fallback to &sw if it's not available. This is also written in the Help
page of shiftwidth.
> indent: fix breaking behaviour with #308, fixes #314

- autoload/go/oracle.vim
`g:go_oracle_scope` is splitting on non-word characters, which includes valid import path characters like `/` and `.`. This fixes it to split only on whitespace.
> Fix oracle scope to split on whitespace

- gosnippets/UltiSnips/go.snippets
- gosnippets/snippets/go.snip
This PR adds a new snippet. 
Now, `errt` expands to...
```Go
if err != nil {
t.Fatal(err)
}
```
This complements `errn`, `errn,`, etc.
> feat(snippets) expand `errt` to `if err != nil { t.Fatal(err) }`

- autoload/go/complete.vim
```
http.Handle()
```
When the cursor is at `n` on `Handle` in normal mode, and type `caw<c-x><c-o>`, we expect
```
http.DefaultMaxHeaderBytes()
```
But currently
```
http.DefaultMaxHeaderBytes(()
```
This patch remove trailing brackets (if it's not needed).
> Trim needless bracket

- autoload/go/complete.vim
previous change should be fixed. When trigger omnifunc at `E` on `.Encode()`, still leave `(` at trailing.
> Fix triming bracket

- gosnippets/UltiSnips/go.snippets
- gosnippets/snippets/go.snip
Not sure how widely used this would be, but I have found myself doing this a lot in a recent project refactoring their HTTP handlers. So here it goes...
errr<tab>
Expands to -
if err != nil {
_ <- cursor puts you here; Handle error
return
}
> Snippet to handle error and return

- autoload/go/cmd.vim
- doc/vim-go.txt
- ftplugin/go/commands.vim
This PR provides a new `:GoTestCompile` command to compile tests and create a test binary. It can be used to fix and capture errors before running the tests or to compile a test binary.
Closes #337
> cmd: add GoTestCompile command

- autoload/go/tool.vim
If basename not found in PATH then restore PATH and return empty string
If basename found just return it. Otherwise we could face situation when BinPath returns something like this `D:\home\go\bin/gocode`. Related problem with vimproc https://github.com/Shougo/vimproc.vim/issues/192
> Return basename from BinPath function

- autoload/go/complete.vim
I have had the same problem as @alexaandru for completiion with vimproc on windows https://gist.github.com/alexaandru/d116c229c07983f80b03
This patch fixes the problem. Tested with and without vimproc on windows and linux.
Vimproc requires that arguments for its functions [were escaped](https://github.com/Shougo/vimproc.vim/issues/192#issuecomment-76941582)
`s:gocodeShellescape` doesn't satisfies vimproc requirements for escaping (at least on windows), so I replaced it with `vimproc#shellescape`
> Use vimporc shellescape

- autoload/go/oracle.vim
- doc/vim-go.txt
- ftplugin/go/commands.vim
Includes the latest Oracle changes from https://go-review.googlesource.com/#/c/8243/
- Callgraph mode is removed, there is another tool which does it (http://golang.org/x/tools/cmd/callgraph).
- Referrers mode is now showing the matching lines, so there is no need anymore to parse them manualy (/cc @akavel )
> Oracle changes

- autoload/go/tool.vim
Sometimes when I'm doing `:GoImport %lib%`, I see this error:
```Error detected while processing function go#import#SwitchImport..go#tool#Exists..go#tool#ExecuteInDir:
line    7:
E480: No match: `=dir`
```
> fix 'No match: `=dir`'

- autoload/go/import.vim
Removes the trailing slash when using `:GoImport`, this can happen when you happen to `<tab>` your way to the full path and forget to remove the slash yourself.
> Remove trailing slash when you :GoImport github.com/user/pkg/

- autoload/go/cmd.vim
On Windows, I was having false negatives when using GoTestFunc, and it turns out that the regexp for go test -run doesn't match with single quotes, and so will always pass since it can't find the test. Using double quotes fixes this.
> Use double quotes for regexp in TestFunc

- autoload/go/rename.vim
In the prompt, the default value now is the previous symbol.
You see: vim-go: rename 'xxxx' to: xxx
and then you can edit the symbol by starting from the previous name. Many code refactor tools provides this. It is useful when you want to rename a word to something similar without retyping it.
> Provide default value for rename input

- autoload/go/doc.vim
When `godoc` can't find any package for corresponding query like below,
:GoDoc foobar
`:GoDoc` opens the window for 'not found' result like as below.
2015/04/21 03:58:02 open /usr/local/Cellar/go/1.4.2/libexec/src/foobar: no such file or directory
I fixed this problem with checking the content of result.
With this fix, `:GoDoc` command correctly echoes 'not found' result without opening window as
below.
No documentation found for "foobar".
> Improve to detect 'no documentation'

- syntax/go.vim
* Fix highlighting of X*foo where X is any other syntax match by
removing unnecessary comment-matching protection
* Remove some unnecessary escaping in character classes
Fixes #394.
> Operator highlighting cleanup/fixes

- ftplugin/go/snippets.vim
Because NeoSnippetSource affects only current buffer,
snippets file is not loaded after the second time.
> fix neosnippet support

- autoload/go/cmd.vim
- doc/vim-go.txt
This has `vim-go` check for the `:Make` command provided by Tim Pope's [`vim-dispatch`](https://github.com/tpope/vim-dispatch) before using `make`, and if it's available, uses that instead.  This allows the `GoBuild` and `GoRun` commands to be run in a Tmux split instead, which is both asynchronous and a _lot_ faster.
I did a little profiling, and it seems like the performance increase is pretty significant
**`:GoBuild` profiling**
| Time | `make` | `Make` (Dispatch) |
| :-- | :--         | :-- |
| Total | 1.055178 s | 0.173488 s |
| Self | 0.016310 s | 0.008696 s |
If you want to check out the full profiling that I did, you can find the files [here](https://gist.github.com/alexlafroscia/d7d351c6fc9834efebe9)
> Use Dispatch when available

- ftdetect/gofiletype.vim
- syntax/gohtmltmpl.vim
- syntax/gotexttmpl.vim
By default all .tmpl files will use the html/template syntax highlighting. However, you can apply highlighting to any file by using `:set syntax=gohtmltmpl`
> Add templates syntax highlighting 

- syntax/go.vim
The documentation tells that this setting is disabled by default, but it was not.
> Change highlighting setting according to documenation

- autoload/go/tool.vim
We need to cd into the current files directory. This is important so
fnamemodify does create a full path for outputs when the token is only a
single file name (such as for a go test output, i.e.: 'demo_test.go').
For ther outputs, such as 'go install' we already get an absolute path
i.e.: '../foo/foo.go') and fnamemodify successfuly creates the full
path.)
Fixes #404,#407
> tool: fix ShowErrors for various go cmds

- autoload/go/cmd.vim
There is no auto jump to errors for `:GoInstall`. All other commands have this. Just adding the missing piece.
> cmd: auto jump to error for :GoInstall

- autoload/go/cmd.vim
These are custom commands which don't use :make so vim's `autowrite`
doesn't take into action. Let us invoke it manually if the user has
this setting turned on.
Fixed by @uli-go
Closed #417
> cmd: autowrite install, test, coverage and vet commands

- autoload/go/fmt.vim
Previously we were calling gofmt/goimports twice when the command was
successful. First we call it so we can catch any errors and display
it(in quickfix window), if there is no errors, we called it again,
purely so we could pipe the commands output (which in our case is the
formatted output) directly to the current buffer. This was very fast
for gofmt, but with goimports it was slow.
Now, we don't call the command again if it's successful, instead we
just replace the output of the first command with the current buffer.
This is actually so obvious and I'm thinking why I didn't I this in the
first place. Humans ...
> fmt: don't call command twice for successful output

- autoload/go/doc.vim
The no such file string appears in 'os' package's documentation, so it erroneously claims that documentation wasn't found. Forcing it to only match that string if it is found at the end of the content allows `:GoDoc os` to succeed, but `:GoDoc osx`, for example, to still fail.
> fixed godocNotFound to not match 'os' pkg contents

- README.md
- autoload/go/cmd.vim
- autoload/go/complete.vim
- autoload/go/def.vim
- autoload/go/errcheck.vim
- autoload/go/fmt.vim
- autoload/go/lint.vim
- autoload/go/oracle.vim
- autoload/go/package.vim
- autoload/go/path.vim
- autoload/go/rename.vim
- autoload/go/tool.vim
- autoload/go/util.vim
- autoload/go/vimproc.vim
- doc/vim-go.txt
- ftplugin/go/tagbar.vim
- plugin/go.vim
This PR includes new features and improvements which brings better support for multiple `GOPATH`s  and tools that support this (such as `godep`). This also creates a foundation for other new project based building tools, such as `gb`. 
The  changes are : 
* A new `:GoPath` command that displays the current set `GOPATH`. It changes the current `GOPATH` when an argument is passed, i.e: `:GoPath /home/fatih/mypath`
* A new `:GoPathClear` command that clears the previous set `GOPATH` via
`:GoPath` and restores it to the initial` GOPATH` value. the current set
`GOPATH`.
* A new `go_autodetect_gopath` setting. This is enabled by default. When enabled, vim-go automatically modifies the `GOPATH` if a project uses a certain package tool (such as `godep`). For now only `godep` is supported. If a …
> Gopath detection and support for godep. Closes #425

- plugin/go.vim
Fix GoUpdateBinaries to support using the git url.<base>.insteadOf
configuration. `go get` is already fixed on the tip of the go sources, but
GoUpateBinaries with go1.4 fails to update any binary whose remote.origin.url
is not the custom import path.
relates to golang/go#10791
> support git url.<base>.insteadOf and custom import paths of binaries

- autoload/go/oracle.vim
- autoload/go/package.vim
- autoload/go/util.vim
- doc/vim-go.txt
- ftplugin/go/commands.vim
1. Add new `:GoOracleScope` with following usages:
*. `:GoOracleScope` prints the current custom scope
*. `:GoOracleScope fmt github.com/fatih/color` sets the custom scope from given arguments. It overrides the `g:go_oracle_scope` argument.
*. `:GoOracleScope ""` clears the scope and unsets it
2. Add package completion to `:GoOracleScope`. So  when we hit `tab` for the following command `:GoOracleScope gith...`  it'll be completed to `:GoOracleScope github.com/...` with possible results to complete the finish. It completes any package in `GOPATH`
3. This PR also includes a fix where the completion would show duplicates paths for completion results, such as `github.com/fatih/color` and `github.com/fatih/color/`. 
These are improvements for #423. 
/cc @tsenart
> Oracle improvements

- autoload/go/cmd.vim
- doc/vim-go.txt
- ftplugin/go/commands.vim
Previously we were using a custom global variable to control the
behavior of jumpting to an error when we called any command in cmd.vim
(such as :GoInstall, :GoTest, etc..)
However we don't need this actually because the default :make command
in vim has the behavior of no jumping to the error when the `!` attribute
is passed to the command, i.e: `:make!`. We have this feature already
for `:GoBuild` and `:GoRun` but those were also conflicting with our
manual `g:go_jump_to_error` setting. Basically even if you call
`:GoBuild` (without `!`) it would not jump if `g:go_jump_to_error` was
set to `0`.
This PR adds the bang attribute, removes the `go_jump_to_error` setting
for the following commands:
* `:GoBuild`
* `:GoRun`
* `:GoInstall`
* `:GoTest`
* `:GoTestFunc`
* `:GoTestCompile`
* `:GoVet` …
> commands: use bang attribute to jump to errors

- autoload/go/def.vim
When using :GoDef on files in a directory containing space, vim would break
with something like: `E484: Can't open file /var/folders/...`
> Don't break when file path contains space

- syntax/go.vim
Fix to match and highlight width and precision in goFormatSpecifier.
```
%s %5s %-5s %5.5f %.5f
```
Using a part of the [Python syntax](https://github.com/hdima/python-syntax/blob/44f1855902b6e2836ff95bec3fc221ad17021ee3/syntax/python.vim#L306).
> goFormatSpecifier width and precision match

- autoload/go/path.vim
This adds a 'vendor' folder under the discovered 'gb' gopath to your gopath. It does not generalize to vendor folders in your existing gopath.
Per the TODO a few lines above, it might make sense to turn this into a configurable option (e.g. an array of 'vendor', 'third_party' searched for as subdirectories of each part of your gopath), but that change is a little more involved and this change does solve a problem for me and, perhaps, others.
> Add gb-vendor plugin's folder to gopath

- autoload/go/fmt.vim
This uses the `-w` flag, which is available both on gofmt and goimports
to replace the current file instead of outputting it. There is no
rewriting on our side anymore, because gofmt/goimport does it outside
VIM now. This should be also very fast as we don't call anything in Vim.
This also includes the improvements from @guns
> Fmt in write

- autoload/go/cmd.vim
- autoload/go/errcheck.vim
- autoload/go/lint.vim
- autoload/go/util.vim
- doc/vim-go.txt
- ftplugin/go/commands.vim
Hi @fatih,
This patch series concentrates on `:GoCommand` argument handling:
1. GoRun, GoTest{,Func,Compile}, GoCoverage, GoGenerate, GoErrcheck, GoLint,
and GoVet can now all handle an arbitrary number of command arguments so
that the user can pass more flags, packages, etc. to respective programs.
This allows for maximum flexibility while still providing simple defaults.
For instance, #461 is addressed with these changes.
2. All command arguments are now properly escaped for shell invocation,
which will avoid bugs involving users that have go source paths with vim
wildcards such as `%` and `#`.
3. All command arguments that will invoked via `makeprg` are escaped with the
`{special}` option of `shellescape` to avoid a double wildcard expansion.
Example:
```vim
" I have go source file at …
```
> Improve :GoCommand argument handling

- ftplugin/go/commands.vim
This fixes the `:GoDrop <pkg>` issue for me., looks like a missing arg in the call. #499
> Fix Not enough args for go#import#SwitchImport when using :GoDrop

- autoload/go/cmd.vim
Running `:Make!` will not update the quickfix list (requires `:Copen`).
As a result the errors from the last build/run are shown which is
exceptionally confusing.
> fix :GoRun with g:go_dispatch_enabled

- autoload/go/errcheck.vim
Currently `:GoErrCheck` show `errcheck analysis...`. It doesn't know how long errcheck analyze complete.
> Change message to PASS after errcheck analyzed without error.

- autoload/go/errcheck.vim
Unify command executing just like we do for the other commands.
> errcheck: fix command for absolute paths

- ftdetect/gofiletype.vim
Setting 'filetype' the second time is as expensive as the first time:
The previous filetype settings are undone using b:undo_ftplugin and
ftplugin, indent, etc. get fully re-sourced because variables like
b:did_ftplugin are removed then.
Thus use :setfiletype to set the 'filetype' only if not done yet.
> Avoid setting 'filetype' twice

- autoload/go/package.vim
- the GOPATH may be in the form of /home/user/go/ or /home/user/go, the
trailing / matters. the match pattern may fail if there is trailing /
> fix bug of handling of trailing /

- autoload/go/import.vim
Currently if I type `GoImport fmt <CR>`, the string `import "fmt "`
will be inserted in my file. This strips leading and trailing spaces
from the path argument to GoImport.
> Strip spaces from path in GoImport

- autoload/go/lint.vim
With recent changes to the way errcheck is called (using ExecuteInDir),
prepending the GOPATH results in invalid expansion.
> Fix path output for GoErrCheck

- autoload/go/lint.vim
- doc/vim-go.txt
- ftplugin/go/commands.vim
Because gometalinter is run using ExecuteInDir, it outputs filenames
relative to the source file being edited, which means that you cannot
open them from quickfix.  By using absolute paths, quickfix output is
usable for jumps.
This change also drops the superfluous go_metalinter_path.
> Use absolute paths for gometalinter, so that filenames resolve correctly

- autoload/go/cmd.vim
> cmd: /dev/null is not supported with go build

- autoload/go/util.vim
This is to fix #537 
If we cant have it this way, maybe we can put a variable in there to override this behavior via .vimrc
> Treat cygwin vim same as normal unix vim.

- autoload/go/rename.vim
- doc/vim-go.txt
- ftplugin/go/commands.vim
- ftplugin/go/mappings.vim
This fixes #566 and also introduces parsing errors for `:GoRename`
command. Now it's acting like our other commands such as `:GoTest`,
`:GoBuild`, etc.. It fully parses the errors and jumps to the first
error it founds.
> gorename: create and populate errors in quickfix window

- autoload/go/lint.vim
- doc/vim-go.txt
Gometalinter has a deadline flag which defaults to 5s.
```
--deadline=5s         Cancel linters if they have not completed within
this duration.
```
This PR adds a `g:go_metalinter_deadline` parameter to customize this time.
> Add deadline flag support in gometalinter

- autoload/go/cmd.vim
- doc/vim-go.txt
> test: timeout after 10 seconds

- autoload/go/cmd.vim
- compiler/go.vim
Tries to fix #287 by dropping from the QuickFix list any items that don't locate existing files.
Known issue: If `cc 1` jumps to a new buffer immediately, the open-buffer message  `"{filename}" {linenumber}L, {colnumber}C` hides the messages that tell the user about the dropped errors. Haven't been able to figure out how to get around that. The messages are just a little "extra" anyway.
Please review when able and let me know if you find any other issues.
> Discard quickfix errors when quickfix doesn't locate a file to jump to

- autoload/go/fmt.vim
When using `go_fmt_options` for `GoFmt`, `GoImports` also use it.
I want to use `-s` option with `GoFmt`, but `GoImports` will not work.
> Disuse go_fmt_options with GoImports

- README.md
There have been a few different issues regarding making `vim-go` and `Syntastic` play well together. The fix I have added to the README in this PR seems to work the best out of all I have seen.
If there is another (better) fix, of course this should be replaced with that... But I believe it is important to have this kind of thing in the README.
> Add note on Syntastic lag to README

- autoload/go/oracle.vim
- autoload/go/tool.vim
- doc/vim-go.txt
- ftplugin/go/commands.vim
When I reading docker source code, which locate in github.com/docker/docker/docker directory, I could not use GoReferrer to find "mainDaemon" when docker as daemon.What I found is client code when docker as client and without golang build tags "daemon".
So I try to add GoTags command,which can set oracle command param "-tags",then thing goes well!
> Add GoOracleTags command to set build tags for oracle

- syntax/go.vim
Some improvements and fixes to the `g:go_highlight_build_constraints` feature:
- add missing `GOARCH` values: `arm64`, `ppc64`, and `ppc64le`
- remove the multiline comment pattern (build constraints must always be line comments)
- add a required trailing space to the build constraint region start pattern to avoid highlighting things like `// +buildwindows` which is not a valid build constraint
- only highlight the leading `//` as a comment; other words in the build constraint can be valid build tags other than `GOOS`, `GOARCH`, `cgo`, and `ignore`, so they should be treated as identifiers
- add a syntax match for package documentation comments that supersedes the build constraint highlighting; with this, you know when you've accidentally written a build constraint that will be ignored …
> build constraint fixes

- syntax/gotexttmpl.vim
This commit sets the goCharacter syntax region to be contained; otherwise,
single-quotes are highlighted as strings outside of the gotplAction regions.
Fixes #603
> Fix goCharacter syntax region to be contained

- autoload/go/cmd.vim
- autoload/go/fmt.vim
- autoload/go/lint.vim
- autoload/go/oracle.vim
- autoload/go/rename.vim
- autoload/go/util.vim
- doc/vim-go.txt
Right now we are just calling `cwindow` without any arguments. By
default Vim opens a view with an height of 10. But this doesn't look
good if you have only on single error. It also takes display estate for 
small screens.
This PR introduces a new feature, which automatically resizes the
quickfix error for the number of errors. However to prevent consuming
all the view, it's capped at 10 lines (the default Vim value).
We also have a new setting, `g:go_quickfix_height` which let us to give
an explicit window height. If set, automatic resize is enabled and the
height will be always the value of `g:go_quickfix_height`.
Previous case:
Improved case (auto height feature):
Closes #592
> util: add auto quickfix window height for errors [GH-592]

- syntax/go.vim
builtins have a very different property from keywords, the identifiers are
settable. It is perfectly valid to override the builtins, though hopefully used
sparingly.
Instead of using `syn keyword`, we now use `syn match` and detect a function
call by searching for an open parentheses.
> syntax/go: do not treat builtins as keywords

- autoload/go/fmt.vim
A simple fix for issue #595.
When :GoFmt is called from within Vim, it runs the gofmt command with the -w parameter, which modifies the source file (actually, it modifies a temp file, which is then swapped in, but you get the idea). One effect of this is that all line endings are changed to lf. When the current buffer is reloaded, vim detects the fileformat as 'unix' due to the lf line endings, even if the fileformat was previously 'dos'. This makes it impossible to maintain windows-style line endings (crlf), if you want them.
Prior to this recent commit: 01578fd8632870f8285266b93c1e219df19c4002, this did not occur. I believe it has to do with the fact that the lines output from gofmt were previously split and inserted line-by-line via Vim itself, which respected the existing fileformat …
> Fix issue #595 - fileformat changed by gofmt

- autoload/go/complete.vim
v:shell_error is readonly variable. So vimproc provide way to get last error. Use it instead of v:shell_error.
> Use vimproc#get_last_status() instead of v:shell_error if using vimproc.

- autoload/go/complete.vim
`if` instead of `let`
Ref: https://github.com/fatih/vim-go/pull/620
> Fix check s:vim_shell_error

- README.md
- autoload/go/cmd.vim
- autoload/go/fmt.vim
- autoload/go/lint.vim
- autoload/go/list.vim
- autoload/go/oracle.vim
- autoload/go/rename.vim
- autoload/go/tool.vim
- autoload/go/util.vim
- compiler/go.vim
- doc/vim-go.txt
Add support for `location list` instead of using `quickfix window`. This allows us to let each window having it's own list of errors displaying. Below is an example of it:
Because of consistency, the previous setting: `go_quickfix_height` is renamed to `go_loclist_height`. (the single breaking change we have)
This is a feature I really like. I also refactored all error parsing, populating, displaying, etc.. functions into a single file to make maintaining much more easier in the future.
> Location list

- autoload/go/lint.vim
- doc/vim-go.txt
- ftplugin/go/commands.vim
- ftplugin/go/mappings.vim
- plugin/go.vim
1. Add the option to run the metalinter on save
2. Add the option to limit the output to the currently active buffer
There is a outstanding PR with the `gometalinter` repo to add some needed logic for this: https://github.com/alecthomas/gometalinter/pull/71 So I assume this PR should not be merged before that one is merged.
Also this the first vimscript code I’ve ever written, so I guess this could be done a little cleaner. Especially the implementation of the `go#lint#GometaAutoSave` func doesn’t feel all that clean to me, but I’m not sure how to do this in a different/better way. So if you have any pointers, I’ll be happy to take them :wink:
> Add additional metalinter options

- autoload/go/cmd.vim
- autoload/go/fmt.vim
- autoload/go/jobcontrol.vim
- autoload/go/list.vim
- autoload/go/term.vim
- autoload/go/tool.vim
- autoload/go/util.vim
- ftplugin/go/mappings.vim
- plugin/go.vim
This PR is going to add a proper initial Neovim integration (to make use of Neovim's advanced features). Nothing needs to be installed or to be done. The features will be active only if you use vim-go inside Neovim. 
Currently implemented features:
* An async launcher and base foundation was implemented for the `go` command. This will be used for all upcoming subcommands of the `go` tool.
* `:GoBuild` is now called asynchronously (it doesn't block the UI anymore). 
* A new `go#jobcontrol#Statusline()` can be used to plug into the statusline. This will show the status of the job running asynchronously
* `:GoRun` opens a new vertical terminal and runs the command there. The terminal mode can be changed with `g:go_term_mode`, which is by default `vsplit`. Current options are `vsplit, split …
> Neovim integration

- autoload/go/tool.vim
Lines without a filenames are actually valid, they belong to multiline
messages. Therefore just add them back as we assume they are a
continuation of the previous message.
fixes #650
> tool: add back valid items to the filter

- autoload/go/rename.vim
Gorename errors were getting swallowed up if we failed to parse them.
Fixes #664.
> gorename: Output original error if error parsing fails.

- autoload/go/cmd.vim
- autoload/go/jobcontrol.vim
When using jobcontrol, assume FAILED if return code is >0. Only prints the first line.
This one is a little messier than the GoRename fix. The non-jobcontrol semantics aren't identical, as it prints the entire output rather than just the first line (but it's more consistent with the GoRename fix).
Let me know if you'd like for me to change it to be consistent. The output on unexpected test failures is typically a panic/timeout, so it's quite big.
> GoTest: Output original message on failure return code

- syntax/go.vim
Fixes the following wrong highlighting:
into:
This is a very weird error. We want to show an error if the chan
statement is in form of:
<- chan
chan <-
The correct form should be of course:
<-chan
chan<-
But for example, if we have a channel of channels (like below), the
selected piece of whitespace is also highlighted as an error
chan<- chan<-
^
Because it's the part of `<- chan`, whereas we should not treat as an
error because we have two `chan<-` and `chan<-` statements.
To fix this, we add a `negative lookbehind` regex statement. It will not
match a text if it's preceded with other text.
First let assemble the current regex for the case: `<- chan`
(receive-only annotation), which is:
\(<-\)\@<=\s\+\(chan\>\)\@=
The first part is:
\(<-\)\@<=\s\+\
Here the pattern \@<= matches with zero …
> syntax: don't pick up chan chains (channel of channels)

- README.md
- autoload/go/asmfmt.vim
- doc/vim-go.txt
- ftdetect/gofiletype.vim
- ftplugin/asm.vim
- plugin/go.vim
This change integrates [asmfmt](https://github.com/klauspost/asmfmt) support for `.s` files, in a similar way to how `:GoFmt` works.
Do take a careful look at this change; I'm not at all a vimscript expert.
> Integrate asmfmt

- ftplugin/go/mappings.vim
RunTerm requires two arguments not one and for creating a new tab the command used is 'tabe' not 'tab'.
> Fixed neovim go-run mappings

- README.md
- doc/vim-go.txt
The neovim integration details have been added in both vim-go.txt and
README.md. Also a little bit of cleanup and consistency fixes.
Fixes #652
> Neovim integration details in vim-go.txt and README.md

- autoload/go/complete.vim
- plugin/go.vim
This is a new feature that prints the information of the completed identifier in statusline. This is experimental.
closes #663
> complete: show identifier information after completion is done

- autoload/go/lint.vim
Errcheck output errors using relative path format but when failed to check packages using absolute path.
Now, absolute path inputed, vim-go errcheck add unnecessary prefix like
```
/your/gopath/your/gopath/filepath.go
```
Errcheck introduced `abspath` options so fixed by using it.
> Fixed errcheck with abspath

- autoload/go/cmd.vim
- autoload/go/jobcontrol.vim
- autoload/go/term.vim
- autoload/go/util.vim
cmd, jobcontrol: add progress and complete message for nvim.
cmd: fix to work GoTestFunc.
refs #686
> cmd, jobcontrol: add progress and complete message for nvim

- autoload/go/package.vim
go#package#Paths for some reason would call go env GOROOT every single
time it needed the GOROOT. In #697 the problem was that it was calling
go to get the GOROOT every single time the statusline needed an update
which resulted in the flashing cursor. Now it only calls it once and
stores it in a script local variable.
> go#package#Paths more efficient at getting GOROOT

- README.md
- autoload/go/alternate.vim
- doc/vim-go.txt
- ftplugin/go/commands.vim
- ftplugin/go/mappings.vim
- syntax/go.vim
In #684 a golang alternate plugin was presented in which it was easy to
alternate between the implementation and testing code. This commit adds
support for that in vim-go. It also adds related documentation and mappings.
> :GoAlternate and related documentation/mappings

- autoload/go/alternate.vim
- doc/vim-go.txt
I also fixed a small bug where if the alternate file was not on the disk
but a buffer it would not switch. Now it does.
> Documentation for the traditional alternate commands

- autoload/go/rename.vim
- doc/vim-go.txt
What do you think about this? Most of the time I rename something completely different.
> Do not prefill GoRename

- ftplugin/go.vim
Seems like YCM is setting it's own omnifunc and also started to use
gocode itself recently. This makes vim-go very slugish and also breaks
it. I really hate it as YCM tries to do a lot of things (such as
GoToDefinition). Now it's not compatible anymore with vim-go because it
tries to do the completion itself instead of letting the application do
it.
> complete: fix ycm

- README.md
- autoload/go/cmd.vim
- autoload/go/fmt.vim
- autoload/go/jobcontrol.vim
- autoload/go/lint.vim
- autoload/go/list.vim
- autoload/go/oracle.vim
- autoload/go/rename.vim
- autoload/go/term.vim
- doc/vim-go.txt
* Prefer the quickfix window for commands whose output is considered to
be errors for more than current buffer. e.g. :GoBuild.
* Prefer the location list window for commands whose output is related
specifically to the current buffer only (e.g: :GoFmt and
:GoImplements).
* Rename 'g:go_loclist_height' to 'g:go_list_height'.
* Add a new option, 'g:go_list_type', to configure whether to always use
the quickfix window, a location list window, or to vary based on the
preferred window as documented above.
@fatih I'm not sure if you'd want to keep the default as I've coded it. The default here is to vary the list by the command, but that changes the 1.4 behavior, and we'd talked about preserving the 1.4 behavior by default.
I tried to update the relevant documentation where the location list was …
> support configurable list types

- indent/gohtmltmpl.vim
Before when write go code in templates, it is not indented correctly,  for example:
```
{{if true}}
hello world
{{end}}
```
I think this should be indented to:
```
{{if true}}
hello world
{{end}}
```
This pull request did the job, fixed the indention for `if/else`, `range`, `with`, `block`, `define`
> Indent code in Go HTML templates

- autoload/go/fmt.vim
"goimports -srcdir" fixes problems with vendoring.
> add support for goimports -srcdir in Format

- autoload/go/cmd.vim
- ftplugin/go/mappings.vim
For some reason, we forgot about this feature in neovim. In vim you can
run `:GoRun main.go` so that other files in the same directory do not
interfere. E.g. if I have the main function defined in another file, a
bunch of random c files etc.
> Allow GoRun to accept file arguments in neovim

- autoload/go/fmt.vim
> fmt.vim: check only once for goimport compatibility

- autoload/go/complete.vim
```go
package main
import (
"log"
"net/http"
)
type fileServer struct {
*http.Server
}
func (s *fileServer) initializeTLS(cert, key string) {
log.Print("hi")
}
```
Watch this short video for the explanation.
https://youtu.be/ruyVHQt9dUY
Sorry about the whispering, 5 in the morning.
This is just a quick fix, imo we need a different offset function for going as if I have my cursor on the `*` it gives me panics, the function should be smart enough to realize where the cursor should be for gocode to be successful.
> the cursor offset for goinfo has to be 1 greater than it currently is

- syntax/go.vim
Before/after:
* Bad octals as errors (`0709`, `081`)
* Hexadecimal integers starting with `OX` (`0XdeadBEEF`)
* Imaginary numbers with exponents (`1E6i`, `0.5e3i`)
* Negative numbers of all types
Periods at the beginning/end of floats seem to not be highlighted -- this is consistent with a bunch of other syntax scripts, but if anyone is a highlighting wizard and knows why, please let me know!
> Improve highlighting for numbers

- autoload/go/alternate.vim
Also throughout the code I see many raw calls to print error messages. We should move the rest of the code to use use `go#util#EchoError()`.
> alternate.vim: handle empty buffer names and general improvements

- autoload/go/complete.vim
- ftplugin/go/commands.vim
- ftplugin/go/mappings.vim
- plugin/go.vim
`Info()` will not echo `PANIC PANIC PANIC` if it's called from the
autocommand.
@peterhellberg what do you think?
> goinfo improvements

- autoload/go/complete.vim
- autoload/go/def.vim
- autoload/go/oracle.vim
- autoload/go/rename.vim
- autoload/go/util.vim
> refactored duplicate offset functions

- autoload/ctrlp/decls.vim
- autoload/go/path.vim
- autoload/go/textobj.vim
- doc/vim-go.txt
- ftplugin/go.vim
- ftplugin/go/commands.vim
- plugin/go.vim
This PR adds the following new features and improvements:
* A vim-go specific tool, called motion is being developed which
provides us the underlying foundation for the following and upcoming
new features.
* `]]` and `[[` motions can be used to jump between functions
* `if` and `af` are improved and implement from scratch. It has now
support for literal functions, comments of functions, better cursor
position support and more stable.
* New `:GoDecls` and `:GoDeclsDir` commands that are available if
`ctrlp.vim` is installed and available. Once called one can easily
jump to any generic declaration available.
All the features above are highly customizable with changing settings
for each of feature. The settings are described in detail in
docs/vim-go.txt
> motion support

- autoload/go/cmd.vim
- autoload/go/jobcontrol.vim
Hi, I'm working on nvim integration of my coverage plugin: https://github.com/t-yuki/vim-go-coverlay
However, I've realized that go#cmd#GoCoverage is not integrated with nvim yet and several API changes are required for better integration.
Moreover, I guess that a recent change 579dd89f broke go#cmd#GoTestFunc because go#util#Shelllist also escapes "-run" flag.
So I want to include changes:
* cmd: fix GoTestFunc is not working
* cmd: show testing and test pass message in GoTest on neovim
* jobcontrol: add AddHandler and RemoveHandler API to catch on_exit callback for callers of caller
* cmd: add neovim integration for GoCoverage
However, I used ugly event handler method to track job status by go#cmd#GoTest and go#cmd#GoCoverage function. Another solution is welcome.
refs #607
> Neovim integration for GoCoverage

- doc/vim-go.txt
- syntax/go.vim
I'd like to disable this feature, so I added an option.
> Add go_highlight_format_strings option for printf-style format strings

- autoload/go/fmt.vim
The system command would break when a path like '/test/path (0)/ok' was
escaped with fnameescape. The shellescape function seems to handle
these cases better.
> fmt: use shellescape instead of fnameescape

- autoload/go/def.vim
- autoload/go/ui.vim
- autoload/go/util.vim
- doc/vim-go.txt
- ftplugin/go.vim
- ftplugin/go/commands.vim
- plugin/go.vim
- syntax/godefstack.vim
> Add custom godef jump stack (fixes #667)

- autoload/go/cmd.vim
Support godoc example tests ([described here](https://golang.org/pkg/testing/#hdr-Examples)) in `go#cmd#TestFunc()`
> GoTestFunc: support testable examples

- autoload/go/def.vim
When the line from godef is `C:\foo\bar\baz.go:123: descriptions`, `split(out, ":")` break the paths on windows.
> Handle windows paths

- README.md
This clarifies in the README that none of the mappings are enabled by default. I completely glanced over the "here are some examples" and assumed these mappings were enabled by default. I was wrong.
Great work on the plugin! Loving it so far :smile:
> Clarify that mappings are enabled by default

- CHANGELOG.md
- autoload/go/coverage.vim
- doc/vim-go.txt
- ftplugin/go/commands.vim
- ftplugin/go/mappings.vim
Also change :GoCoverage to rerun the tests. Now we support two ways of
working with coverages if needed.
Closes #806
> coverage: add :GoCoverageClear and :GoCoverageToggle

- gosnippets/UltiSnips/go.snippets
- gosnippets/snippets/go.snip
This just adds a couple simple snippets for creating http handler functions.
> Add http handler snippets

- README.md
Add a note in the readme about using quickfix lists to work around an issue when
using syntastic.
For details, see #814 and https://github.com/scrooloose/syntastic/issues/1650
> Document using quickfix list for syntastic

- gosnippets/UltiSnips/go.snippets
- gosnippets/snippets/go.snip
> Snippets for Example and Benchmark

- autoload/go/path.vim
- plugin/go.vim
I asked this on #188 but since that's a closed PR I feel like it's less likely to receive attention so I'm creating a new issue instead.
I have to start this with the question: is there any particular reason for append instead of prepend? This is causing issues if people have some other binary in their path with a colliding name, because appending makes our gobin the last lookup path rather than the first.
I'm getting several reports of people hitting this issue because they had tools compiled on 1.6 and were hanging out in their `$GOPATH/bin` and now that we're using `g:go_bin_path` that is not getting updated, short term fix for us is just removing those stale binaries but seems like a prepend to the `$PATH` would be appropriate.
I made this as a PR because this may be the right …
> don't default to binaries in the PATH

- autoload/go/impl.vim
- autoload/go/util.vim
- doc/vim-go.txt
- ftplugin/go/commands.vim
- plugin/go.vim
This adds the plugin https://github.com/rhysd/vim-go-impl with the
following changes/improvements:
* `:GoImpl` can be now called without any arguments, in this case it
assumes the identifier under the cursor to be the receiver type
* `:GoImpl io.Writer` is a valid usage now, in this case it assumes the
identifier under the cursor is the receiver type
* Removed the restriction for completion that there needs to be at least
three words. This is neede because `:GoImpl io.Writer` is now a valid
expression.
* We use now `go doc` for the auto completion. This allows for example
the following usage as well `:GoImpl json.`, in this case you can now
complete to json.Unmarshaller, whereas `godoc` is not capable of doing
it.
* There is a newline prependend before we put the generated method stubs
* …
> impl: add vim-go-impl

- autoload/go/rename.vim
After a long time I had now some time to look at it. So first this can
be solved easily with
```
set autoread
```
But this is problematic and doesn't work well in Vim. Here is a mailing
list post (yeah I know it's 10 years old but hey it still applies!:
http://www.mail-archive.com/vim@vim.org/msg05900.html)
That's why people add additionaly an autocmd in form of:
```
set autoread
autocmd BufEnter *.go silent! checktime
```
This triggers automatically checktime, which triggers to reload any
other file that was changed outside Vim. This works perfectly for
`:GoRename`.
But we don't need the autocmd, that would otherwise call checktime for
every single buffer we enter. Instead we only call it explicitly if
`:GoRename` is being called.
Closes #351
> rename: reload all files to reflect the new changes

- autoload/go/package.vim
Allows guru tools to work with gb, godep, etc
> Add non-standard workspaces to package path list

- autoload/go/lint.vim
- autoload/go/textobj.vim
> lint: escape directory for shell invocation

- autoload/go/fmt.vim
- autoload/go/path.vim
#823 added this the wrong way, it was reverted back on 9f0cf00f6e9a437b738959f629ca29658334c6b5 but still not achieving the right functionality.
This uses it properly now, also adding it to how we lookup goimports for srcdir support.
> Properly use exepath for CheckBinPath

- autoload/go/cmd.vim
- autoload/go/doc.vim
- autoload/go/guru.vim
- autoload/go/tool.vim
Hi,
some of the `:Go*` commands report errors when tcsh is configured in Vim. This pull request aims to resolve these errors.
I tested the commands with tcsh and sh configured, and here it works fine. Maybe someone else can double check if everything still works smoothly with her/his shell.
> Increase compatibility with tcsh

- README.md
- doc/vim-go.txt
- plugin/go.vim
Not all GOPATHs are made equal and some don't work well with `go get -u`. This allows users to disable the `-u` for `go get`'s.
cc @si74
> make go get -u configurable

- README.md
- doc/vim-go.txt
- syntax/go.vim
Adds the ability to differentiate `go.fields` & `go.methods()`.
Parses out `bar`
`foo.bar`
`foo.bar =`
`foo.bar:`
`foo.bar()`
I'm not sure what the default highlight should link to, so as of now it's `Type`, tho this should be change.
> add goField

- autoload/go/cmd.vim
Neovim didn't like escaping it. Just disable it.
Closes #899
> coverage: fix running coverage for neovim

- autoload/go/cmd.vim
- autoload/go/jobcontrol.vim
> cmd: fix :GoTestCompile leaving behind artifacts

- autoload/go/def.vim
> def: support modified files

- README.md
- doc/vim-go.txt
- syntax/go.vim
Look behind regexp patterns are not recommended in syntax files,
especially with the new NFA engine. So we should try to avoid them.
Highlighting of methods, fields, methods, structs and interfaces should
be much faster now.
Consolidated two options g:go_highlight_structs and
g:go_highlight_interfaces into one g:go_highlight_types.
> Various improvements to syntax highlighting.

- syntax/go.vim
If `g:go_highlight_types` is set to 0, the `type` keyword is not highlighted. This pull request fixes this issue.
> fix highlight type keyword

- autoload/go/template.vim
- autoload/go/tool.vim
- autoload/go/util.vim
- doc/vim-go.txt
- plugin/go.vim
- templates/hello_world.go
This is a new feature that fills the content of a new file according the
to current directories context. If there are no Go files, a simple hello
main package is created, otherwise a file with package declaration
based on the current package is created.
Demo:
> Fill the content of a new file automatically based on the context

- autoload/go/util.vim
- doc/vim-go.txt
- gosnippets/UltiSnips/go.snippets
Now the `json` snippet expansion is much more smarter. It does the followings:
* The placeholder is pre populated according to the first word in the line
* It automatically converts it to either `snakecase` or `camelcase`
Demo:
> snippet: make json field tag expansion smarter

- syntax/go.vim
Fixed issues reported by @svanharmelen in comments of pull request #917.
- do not highlight method receiver if g:go_highlight_types is not set
- fixed highlighting of anonymous functions
> small syntax fixes

- autoload/go/guru.vim
- doc/vim-go.txt
- ftplugin/go/commands.vim
- ftplugin/go/mappings.vim
- plugin/go.vim
- syntax/go.vim
Carried https://github.com/fatih/vim-go/pull/933 over to here with additional improvements and fixes.
> implement :GoSameIds

- autoload/go/guru.vim
- syntax/go.vim
Move the modification of the goSameId highlight group from
autoload/go/guru.vim to a proper definition in syntax/go.vim so that
users can customize it.
> allow goSameId highlight group to be overridden

- autoload/go/guru.vim
Only clear the highlighted identifiers after running Guru to reduce the
flicker time.
It's a very minor improvement, and probably barely noticeable on some machines, but on a large modified buffer with a slow disk drive it may be more significant.
> reduce flicker when using go_auto_sameids

- plugin/go.vim
I find sometimes want to change the settings of vim-go that control whether or not some actions happen in response to events (e.g. formatting, linting, etc.). This change allows the settings to be changed at runtime instead of having to restart Vim to pick up the changes.
There were a couple of `autocmd` entries where I removed the `nested` argument, because it didn't seem to be necessary.
> allow auto features to be disabled without restarting Vim

- autoload/go/asmfmt.vim
- autoload/go/fmt.vim
> Restore original files permissions

- syntax/go.vim
Replace 'he=e-1' with '\ze' to avoid conflicts with other highlight plugins (e.g. luochen1990/rainbow).
> Replace 'he=e-1' with '\ze'

- autoload/go/fmt.vim
make sure that we pass a valid parameter to setfperm function.
> go#fmt#Format fails on new unsaved files

- autoload/go/coverage.vim
- syntax/go.vim
This let's the user override those if they don't like it.
Closes: #960
> syntax: add goCoverage specific highlights

- autoload/go/guru.vim
- ftplugin/go/commands.vim
- ftplugin/go/mappings.vim
Auto sameIds is cool, but it doesn't behave nicely in large files, where scolling the screen causes the cursor to move and therefore change the identifier that's being matched. This change allows me to quickly turn on and off same-id highlighting, and have the highlighting stay in effect as I scroll through the file.
> Add ToggleSameIds

- autoload/go/tool.vim
Tested on Mac OS X using bash/zsh as Vim's shell, Linux with bash/zsh as Vim's shell and on Windows 10.
Fixes #959.
> tool: use double quotes in PackageName for Windows compatibility

- syntax/go.vim
Also this group should be highlighed when g:go_highlight_operators is enabled.
Fixes #977
> goVarArgs highlight groups is too greedy.

- autoload/go/cmd.vim
- syntax/go.vim
Contains from #976 `1` and `2`:
```
1) Added back guifg attributes for GoCoverage highlighting (this broke on colours for gvim and truecolors neovim)
2) Made GoInstall obey alternative $GOPATH, so the binaries get built correctly when godeps is used.
```
cc @wladh
> Fixes from wladh

- README.md
I've been using SimpleAutoComplPop  for go programming for a while.
I believe it can be a simple alternative for realtime auto completion with vim-go.
> add SimpleAutoComplPop to the list

- autoload/go/util.vim
This makes sure the commands still work when using a non-Bourne shell such as
fish or tcsh.
:help vim-doc recommends:
set shell='/bin/sh'
But this is not a great solution. This will mean that `:sh` will now invoke
`/bin/sh`, instead of `tcsh` or `fish`. It also means that things such as shell
aliases for `:!` will no longer work.
> Reset shell before running a command in go#util#System

- autoload/go/template.vim
Add `fnameescape()` to handle any special characters within a template path.
Example: usage of `hello_word.go` template with a space within path is broken.
> Escape all template path special characters

- autoload/go/asmfmt.vim
- autoload/go/complete.vim
- autoload/go/fmt.vim
- autoload/go/lint.vim
- autoload/go/template.vim
- doc/vim-go.txt
- ftplugin/go/commands.vim
- plugin/go.vim
Add commands to toggle settings that control automatic behaviors. All the new commands begin with `GoToggle`, and are suffixed with the name of the setting, but using PascalCase in place of snake_case.
Also moved one function so that all functions called by events and functions that control settings are in the same relative order as the respective events.
> add commands to toggle settings that control auto behavior

- autoload/go/util.vim
Don't reset it on Windows, and only reset it if `/bin/sh` is executable (which
should pretty much always be the case, but it's not in POSIX and IIRC POSIX
explicitly advises against relying on it).
This is basically the same method that vim-plug uses.
This improves #967 and should fix #986.
> More robust resetting of the shell.

- README.md
- doc/vim-go.txt
- This merges @svanburen 's PR #935 − resolving the conflicts.
- Sync "troubleshooting" section with the one on the Wiki. IMHO we're probably best off deleting the wiki page after this is merged?
- Mention Vim's packages feature for installing.
- Run [vimhelplint](https://github.com/machakann/vim-vimhelplint) and fix all the reported errors. Many are boring line width changes, but there were also quite a few "missing link" errors (e.g. `|g:go_foo|` instead of `|'g:go_foo'|` was used).
- Add a few settings that were undocumented.
- Fix a few minor typos.
> Doc cleanup

- autoload/go/def.vim
- autoload/go/guru.vim
Pass the -modified flag and the buffer contents to guru on stdin when
the buffer has been modified instead of having to manage a temp file
manually.
> use guru's -modified flag

- syntax/go.vim
This does three things:
- For light backgrounds the "highlighted" text is typically the same colour as
the normal text:  ![2016-08-01-060201_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1032692/17283412/4ad4170c-57b0-11e6-9afb-d1f518175926.png)
So use the `background` setting to set a more appropriate colour.
I know I can set my own colour, but it would IMHO be better if it just
works by default.
- The second issue is that most (if not all) colour schemes do this at the
start:
" Remove all existing highlighting and set the defaults.
hi clear
Which resets all custom highlight groups (except for `:hi link`). So just
using a "bare" `:hi ctermfg=...` won't work after changing colour schemes:
:hi goSameId
goSameId       xxx term=bold cterm=bold ctermfg=0 ctermbg=121
:colorscheme …
> Fix :GoSameIds for light background, GUI, and after changing colour schemes

- autoload/go/package.vim
- ftplugin/go/tagbar.vim
Filepath backslash-related problems.
> Fixed Windows tagbar&GoCallers errors with g:go#use_vimproc=0.

- autoload/go/guru.vim
When g:go_auto_sameids is not set, re-apply :GoSameIds after the buffer
is displayed in a window. This ensures that once the user has called
:GoSameIds, the highlighting will be applied in the buffer based on the
cursor position at the time of evaluation until the user calls
:GoSameIdsClear, even if the buffer is reloaded into the same window (
e.g. :GoRename, or even reloading the file from disk manually).
> Re-evaluate sameids after buffer is re-entered

- doc/vim-go.txt
Add `go_highlight_generate_tags` in `doc/vim-go.txt`
(Related PR is https://github.com/fatih/vim-go/pull/757.)
Thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fatih/vim-go/1023)
> Add go_highlight_generate_tags in docs

- autoload/go/def.vim
> update jumplist in :GoDef

- doc/vim-go.txt
I turned on `g:go_auto_sameids` and nothing happened, in contrast to your tutorial. Then I investigated and found out that the cursor needs to rest at the same position at least for `updatetime` ms, which means 4s by default. That's way too long for me.
I've added a hint for `updatetime` in the manual, and thereby fixed a sentence that was incomplete.
> SameIds: Fix Sentence, add hint to 'updatetime'

- autoload/go/doc.vim
Support getting documentation for the identifier under the cursor in a modified buffer.
> allow :GoDoc on modified buffers

- syntax/go.vim
It should not highlight format specifiers in strings like "something %%c".
> Fix syntax goFormatSpecifier: check '%%'

- doc/vim-go.txt
- ftplugin/go/commands.vim
Hi!
I've changed the `:GoMetalinterAutoSaveToggle` command name to become `Linter` because the command calls `go#lint#ToggleMetaLinterAutoSave()` which has already defined `MetaLinter`.
So, I just chose "`MetaLinter`" to the command name.
Thanks!
> Rename GoMetalinterAutoSaveToggle to GoMetaLinterAutoSaveToggle

- syntax/go.vim
Currently, nested or chained fields are not getting highlighted.
This will change that to this:
> Highlight nested fields or chained fields

- syntax/go.vim
exclude iota and nil from `goBoolean`
It would be better to treat them separately.
Thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fatih/vim-go/1030)
> Exclude iota and nil from goBoolean

- autoload/go/path.vim
Older checking v:version is wrong for 800.
> fix check v:version for vim 8.0

- autoload/go/complete.vim
Windows doesn't work with `unix`. ref https://github.com/fatih/vim-go/pull/1000
> fix default sock type

- doc/vim-go.txt
This replaces a reference to `go_highlight_{structs,interface}` in the doc
with `go_highlight_types`.
> Fix reference to go_highlight_{structs,interface}

- autoload/go/cmd.vim
see original issue #1042 (:GoBuild -tags 'debug' causes issue in neovim)
> skip go#util#Shelllist if nvim is being used

- syntax/go.vim
`g:go_highlight_methods` highlights method calls, but `g:go_highlight_functions` does not highlight function calls.
So this PR adds the same highlighting for function calls as well. See the examples below where the call to `demoFunc()` is not highlighted initially where the call to `demoMethod()` is.
Before:
After:
> Add support for highlighting function calls

- LICENSE
Update license to credit Renee French for original Go Gopher design, since the awesome new Vim-Gopher image has recently been added to the repo.
I placed in the license file since other prominent Go sites, even golang.org don't directly credit Renee on the main page.
> Update license to credit Renee French for Gopher

- autoload/go/complete.vim
- doc/vim-go.txt
gocode recently added support for unimported packages.
https://github.com/nsf/gocode/commit/57b3fab1de11102eee896051605108949fbe75da
This comes in handy for example when you know approximately what
function you're looking for but don't remember the exact
name or signature.  It's must faster to get suggestions for
packages without having to import them first.
The feature is optional and must be enabled with `gocode set unimported-packages true`.
Enable the gocode feature by default, but allow it to be configured with
g:go_gocode_unimported_packages.
> Provide completions for unimported packages.

- syntax/go.vim
This will allow nested `struct` to be highlighted.
> Highlight nested structs

- syntax/go.vim
And (again for consistency) change `goMethod` to `goMethodCall` to be consistent with `goFunctionCall`.
@fatih this is of course a much cleaner and better way to support all use cases correctly.
> Make sure builtins are always hightlighted correctly

- plugin/go.vim
Clear the most recent goSameId highlight groups on BufWinEnter so that
the highlight groups do not persist when a different buffer is loaded
into a window.
Fixes #1041
> Clear most recent goSameId highlights groups

- autoload/go/complete.vim
- autoload/go/tool.vim
- autoload/go/util.vim
Add new function to return cached version of Go environment variables.
With that set GOROOT everytime we execute gocode. This will prevent
gocode using the internal embedded GOROOT and will use the GOROOT from
the latest installed Go version.
Fixes #901
> util: add go#util#env function

- doc/vim-go.txt
- plugin/go.vim
Echoing `v:completion.info` after completion is done is annoying if users uses completion other than vim-go omni completion.
When I run completion with completefunc and this completion-item contains multi-line info, vim-go automatically echo this info and it messes up the window.
So, I added this option.
> add an option to show type info when completion is done

- CHANGELOG.md
- autoload/go/cmd.vim
- autoload/go/coverage.vim
- autoload/go/def.vim
- autoload/go/guru.vim
- autoload/go/lint.vim
- autoload/go/rename.vim
- autoload/go/util.vim
+job was introduced in 7.4.x cycle and later at one time it was decided
to release vim with the version number of 8.0. This means that people
having a recent 7.4.x version might have the `+job` feature. But this is
problematic because the initial `+job` implementation is full of bugs.
It was fixed later by many fixes and improvements. 8.0.0087 is the
minimum for *now*, as it fixes another issue about jobs.
We introduce a new wrapper, so we can tweak the requirement ourselves
and tweak the patch level if needed.
> vim: require at least 8.0.0087 for +job features

- autoload/go/coverage.vim
Due to usage of ':t' modifier to extract filename when switching from
file_test.go to file.go, the original path to file is lost and Vim can't
open it if it's stored in some subdir. It only worked by accident if the
file was located in the same directory.
> coverage: allow to run coverage on _test.go files in subdirs

- doc/vim-go.txt
- ftplugin/go.vim
Currently this is hardcoded if you use `g:go_auto_type_info` and/or `go_auto_sameids`, but the docs clearly refer to the standard vim `updatetime` setting.
With this hardcoded setting of 800ms, the user configured value is overwritten which is unexpected and sometimes even not wanted.
> Add `g:go_updatetime` to configure a custom `updatetime`

- autoload/go/coverage.vim
- autoload/go/guru.vim
- autoload/go/rename.vim
Some parts of the code use go package dir relative to the current GOPATH
as a target for statusline update message which leads to their messages
not being displayed in the statusline (because it expects full path to
the package). Fix this by always using full package path.
Signed-off-by: Pavel Borzenkov <pavel.borzenkov@gmail.com>
> Always use full path as statusline target directory

- autoload/go/job.vim
- autoload/go/jobcontrol.vim
Otherwise all previous build errors are shown even after successful
build.
Signed-off-by: Pavel Borzenkov <pavel.borzenkov@gmail.com>
> job: close quickfix window if a job has succeeded

- autoload/go/cmd.vim
- autoload/go/fmt.vim
- autoload/go/guru.vim
- autoload/go/job.vim
- autoload/go/jobcontrol.vim
- autoload/go/lint.vim
- autoload/go/list.vim
- autoload/go/rename.vim
- autoload/go/term.vim
Currently, the `w:quickfix_title` is being automatically set to the actual
Vim command that populates quickfix/location list. For example, running
any Guru command it will be displayed as `:    lgetexpr a:items` which
is not really informative.
> Provide a descriptive quickfix/location list title.

- autoload/go/lint.vim
- autoload/go/list.vim
The last argument was introduced with 7.4.2200. Make sure it's only used
with that version.
https://github.com/vim/vim/commit/d823fa910cca43fec3c31c030ee908a14c272640
Fixes: #1131
> list: set title only for recent Vim versions

- indent/gohtmltmpl.vim
Golang's template has supported a action with a minus sign like `{{-` since go1.6.
Using this syntax breaks the indentation.
> Fix indentation broken when using a action with a minus sign like `{{-'

- autoload/go/jobcontrol.vim
- autoload/go/term.vim
Changes in neovim job control API broke vim-go integration. This commit
updates alters the integration to follow recommended practices from the
neovim wiki: https://github.com/neovim/neovim/wiki/Following-HEAD#20161212
> fixes #1144: "E118: Too many arguments for function: <SNR>173_on_exit"

- autoload/go/guru.vim
`:GoDescribe` and other `guru` functions failed with 
```
Error detected while processing function go#guru#Freevars..<SNR>33_run_guru..<SNR>33_sync_guru..<SNR>33_guru_cmd:
line   42:
E107: Missing parentheses: result.tags = tags
```
This change fixed this for me and now `:GoDescribe` works.
> fix bug in guru vim script

- autoload/go/template.vim
- doc/vim-go.txt
This adds an option to use the directory name that contains a package as the name of the package instead of using a template, as requested in issue #1053
> Add option to use cwd as package name instead of template

- autoload/go/def.vim
Handle jumping to type definitions from a modified buffer. When the
definition is in the same file, skip trying to open the file that
contains the definition - just set the cursor position. When the
definition is in a different file and the current buffer has unsaved
modifications, use :hide edit instead of :edit.
Fixes #1125
> handle :GoDef from modified buffer

- autoload/go/def.vim
Properly pop to the requested location in the jump list, even when the
current buffer is modified. When current buffer is the target, don't try
to load the target file using edit or hide edit; just set the cursor
position. When the current buffer is modified and is not the target, use
hide edit to hide the current buffer.
> allow popping from jump list when buffer is modified

- autoload/go/cmd.vim
- autoload/go/coverage.vim
- autoload/go/def.vim
- autoload/go/guru.vim
- autoload/go/lint.vim
- autoload/go/rename.vim
Use funcref() instead of function() to get a Funcref that will retrieve
the function by reference instead of by name. function() returns a
Funcref that resolves the function by name, which caused multiple
concurrent jobs of the same type to both execute the callback that
closed over the arguments of the last job to be started. funcref()
returns a Funcref that returns the function by reference (not by name),
so each job is assured that its callbacks execute the function that
closed over the arguments of that job.
Also refactored a couple of the guru functions to check the result of
guru_cmd for stdin_content explicitly instead of assuming that
guru_cmd's result has a stdin_content key when the buffer is modified.
The easiest way to see the problems that this PR addresses is to set …
> use funcref() instead of function() for closures used as callbacks

- autoload/go/guru.vim
Fix the check for a buffer-local BufWinEnter autocmd in
go#guru#ClearSameIds() so that multiple BufWinEnter autocmds are not
registered to rehighlight the sameids when re-entering the local buffer.
> clear buffer-local BufWinEnter properly

- autoload/go/lint.vim
After splitting `go_metalinter_command` it is already a List. Wrapping the result inside another list causes a "using List as a String" error and linting to fail.
> Use go_metalinter_command as List after split().

- plugin/go.vim
Go 1.8 has a default GOPATH (~/go) , if there is no GOPATH set we should also check for the value of go env GOPATH before bailing out.
> If GOPATH is empty check for the value of go env GOPATH

- autoload/go/lint.vim
This change is for issue #1142.
Previous to this change, the option g:go_metalinter_deadline would only
be respected when calling gometalinter if we called it synchronously.
This change removes the default value of g:go_metalinter_deadline of 5
seconds.
For async mode: We pass in a --deadline option now only if we've defined
g:go_metalinter_deadline. For sync mode: We always pass in a --deadline
value. If g:go_metalinter_deadline is not set, we pass in 5 seconds.
Please note that gometalinter itself has a default deadline of 5 seconds
if no deadline is passed to it, so in either case the default of 5
seconds will apply.
> #1142: go_metalinter_deadline applies in async mode now

- autoload/go/doc.vim
gogetdoc now includes import paths for package doc too.
We now detect package doc by checking the decl field.
Fixes #1173
> Fix :GoDocBrowser for third party package doc.

- autoload/go/cmd.vim
- autoload/go/jobcontrol.vim
1. honor `g:go_echo_command_info` when dispatching builds in neovim
1. fix `:GoBuild` error in neovim due to invalid jobcontrol handler function signatures (`s:on_stdout`, `s:on_stderr`)
1. update statusline before and after `go#jobcontrol#Spawn` command is executed
also, as an aside, it looks like vim's job capability is utilized much more than neovim's job-control. it would be nice to abstract the differences and bring neovim up to parity again.
> fix :GoBuild issues in neovim

- README.md
Thank you for this awesome plugin!
This PR aims to add consistency to the README mappings examples
If you prefer them capitalized then I can update this PR to make all `<leader>` `<Leader>`
> Lowercase <Leader> in mappings examples

- gosnippets/UltiSnips/go.snippets
- gosnippets/snippets/go.snip
In the most cases I write `if err != nil {}` is this.
> log.Fatal(err) is useful

- autoload/go/asmfmt.vim
- autoload/go/complete.vim
- autoload/go/def.vim
- autoload/go/doc.vim
- autoload/go/fmt.vim
- autoload/go/guru.vim
- autoload/go/textobj.vim
- autoload/go/util.vim
All of files should be written in utf-8 if the file will be passed to external command.
> Support 'encoding != utf-8'

- autoload/go/guru.vim
When reporting the value of the Guru tags, the `a:1` variable is used. The `g:go_guru_tags` variable should be used instead.
> Correctly report the value of the 'g:go_guru_tags' variable

- autoload/go/path.vim
This can happen if, for example, you don't currently have a $GOPATH set.
> Ensure no trailing : in gopath

- autoload/go/tags.vim
- autoload/go/tags_test.vim
- autoload/go/test-fixtures/tags/add_all_golden.go
- autoload/go/test-fixtures/tags/add_all_input.go
- autoload/go/test-fixtures/tags/remove_all_golden.go
- autoload/go/test-fixtures/tags/remove_all_input.go
- doc/vim-go.txt
- ftplugin/go/commands.vim
- plugin/go.vim
- scripts/test.sh
* Use new [gomodifytags](https://github.com/fatih/gomodifytags) tool to manipulate and modify tags
Checkout demo:
* `:GoAddTags` is able to add tags and options
* `:GoRemoveTags` is able to remove tags and options
Usage:
Following command add multiple tags. Does not modify if the key already
exist. If `,optionaname` is given, it adds the given option to that key.
If called without arguments, it adds by default tags with `json` key.
```
:GoAddTags
:GoAddTags json
:GoAddTags json,omitempty
:GoAddTags json hcl bson
:GoAddTags json,omitempty hcl bson
```
Following command removes multiple tags and options. If `,optionname` is
given, it removes the option belonging to that key instead of removing
the key. If called without arguments, it removes all tags belonging to a
struct.
```
:GoRemoveTags …
```
> New GoTags improvements

- autoload/go/fmt.vim
I want to use goimports's `-local` flag, but vim-go ignores `go_fmt_options` when using goimports for some reason. This just removes that limitation.
> Respect go_fmt_options when running goimports

- autoload/go/fmt.vim
At some point in the near past the location list seems to have broken as shown by https://github.com/fatih/vim-go/issues/1182. When comparing an older version of vim-go and master the difference seems to be due to not including the filename in the location list.
According to the help page for `setqflist()` the filename should be added to the dictionary as the key `filename`. This lead me to pass the filename into the function that generates the individual lines of the location list and then set the file on each error.
This fixes the #1182 on my computer, but my knowledge of vim script is a bit question and would appreciate further verification.
> Set the filename in the location-list

- doc/vim-go.txt
After playing around with vim 8 and a minimal vimrc, I found that noshowmode was the only way to see post-completion usage information.
> Document 'noshowmode' requirement for echo_go_info

- autoload/go/doc.vim
The default behavior for resizing the split when using godoc was to limit the
vertical size, even when using the vertical split. This is now constrained to
only limit vertical size for horizontal splits and vice-versa.
> Modify the resize behavior for godoc

- autoload/go/rename.vim
- doc/vim-go.txt
- ftplugin/go/commands.vim
Reopening issue #389, it seems like `gorename` supports `-tags` flag for a while now, still undocumented however.
See https://github.com/golang/tools/blob/master/cmd/gorename/main.go#L29 for reference.
This patch add support for this flag. I'm sure, I'm not the only one who misses this feature badly.
> Add build tags support for gorename

- autoload/go/cmd.vim
- autoload/go/guru.vim
- autoload/go/rename.vim
- doc/vim-go.txt
- ftplugin/go/commands.vim
Remove also :GoRenameTags and :GoGuruTags as this is a fundamental
feature. No need to duplicate it for each independent tool.
> Add :GoBuildTags to set build tags

- .github/CONTRIBUTING.md
Old link for `doc/vim-go.txt` would lead to the URL https://github.com/fatih/vim-go/blob/master/.github/doc/vim-go.txt
> Updated Broken Link

- doc/vim-go.txt
The GoDef command does not support specifiying identifiers on the
command line due to limitations in the Guru and Godef tools, which
operate on file positions. This change updates the help for GoDef to
remove an incorrect mention of explicit arguments.
> Update GoDef help: remove explicit arguments

- syntax/gotexttmpl.vim
In `text/template` starting from Go 1.6, whitespace around actions can be trimmed with "- " and " -" to result in cleaner output (https://golang.org/pkg/text/template/#hdr-Text_and_spaces). Update `syntax/gotexttmpl.vim` to allow using this construction around comments.
> Allow trimming around comments in gotexttmpl syntax.

- autoload/go/cmd.vim
- autoload/go/fmt.vim
- autoload/go/path.vim
- plugin/go.vim
This PR fixes the following cases:
* If no GOPATH is set, vim-go uses the default GOPATH via `go env
GOPATH` (starting Go 1.8)
* `:GoPath` now shows the correct `GOPATH` if no GOPATH is set
* `:GoInstallBinaries` now installs to the correct GOPATH if no GOPATH
is set
fixes #1243 #1208
> Go 1.8 compatible GOPATH improvements

- autoload/go/cmd.vim
- autoload/go/coverage.vim
- autoload/go/def.vim
- autoload/go/guru.vim
- autoload/go/job.vim
- autoload/go/lint.vim
- autoload/go/rename.vim
When channel's close_cb is called, the job this channel is assigned to
may still be alive and the result status of the job will be set to
FAILED (as no actual return code is available at that moment). This is
easily reproduced for me on a single CPU Linux VPS.
To fix this, check for job's status in exit_cb instead.
Signed-off-by: Pavel Borzenkov <pavel.borzenkov@gmail.com>
> job: fix race between channel close and job exit

- gosnippets/UltiSnips/go.snippets
- gosnippets/snippets/go.snip
This pattern is widely enough used to be a snippet i believe.
Examples from one golang.org example.
```
// ...
if err := cmd.Start(); err != nil {
log.Fatal(err)
}
// ...
if err := json.NewDecoder(stdout).Decode(&person); err != nil {
log.Fatal(err)
}
if err := cmd.Wait(); err != nil {
log.Fatal(err)
}
```
> Include if with inline error handling

- autoload/go/keyify.vim
- doc/vim-go.txt
- ftplugin/go/commands.vim
- plugin/go.vim
Includes support for https://github.com/dominikh/go-tools/tree/master/cmd/keyify
through the `GoKeyify` command.
It turns unkeyed struct literals into keyed struct literals.
> Include keyify support

- gosnippets/snippets/go.snip
Fixed neosnippet errors when loading a go file due to missing indentation.
> Fixed indent for 'ife' snippet

- autoload/go/util.vim
vim-go system calls fails when using tcsh.
Having the [t]csh shells set as the login shell results in
temporary file access errors when calling ksh or dash system
shells. /bin/sh is often aliased to these shells on modern
Linux and BSD systems including VoidLinux, Debian and FreeBSD.
As more Linux systems move away from bash to dash for the system
shell, this issue will occur more often.
> Fixed issue Vim-Go broken on freebsd #1224

- autoload/go/tags.vim
- doc/vim-go.txt
Hey guys, I added a global option to set `gomodifytags`' transform (I like `camelCase` over `snake_case`).
The variable name is `g:go_modifytags_transform` (defaults to `snakecase`, possible values are `camelcase` and `snakecase`)
This is my first time doing Vim script, so if I did something really wrong, please correct me 😄 (Well... It's two lines so what could be wrong)
> Add :GoAddTags transform

- autoload/go/path.vim
> path: return the unmodified GOPATH if autodetect is disabled

- autoload/go/lint.vim
- doc/vim-go.txt
With no arguments passed to GoLint, the golint command will be executed on the current directory.
#1263
> Change GoLint command to lint the current directory

- autoload/go/lint.vim
> do not jump to the quickfix window when metalint

- syntax/go.vim
/\<interface\|struct\>/  would highlight **interface** or **struct** when **interface** was at the beginning of the word or **struct** at the end. By putting this in parenthesis, the word boundary checks correctly.
> Fix Issue #1283 Resolve highlighting error by surrounding expression in \(\)

- autoload/go/fmt.vim
- doc/vim-go.txt
> fmt: add support of 'go_list_type' for :GoFmt and :GoImports

- autoload/go/fmt.vim
- doc/vim-go.txt
* add the ability to specificy binary specific options
* remove `go_imports_bin` settings as it's subject to confusion
Thanks to @cespare for the idea and @hori-ryota for initial code snippet
Fixes #1212
> fmt: change go_fmt_options's type to dict

- autoload/go/list.vim
- autoload/go/statusline.vim
- autoload/go/test.vim
This is an improvement to alter the parse function of go test specific commands. Currently the regex is still the same, but it enables us to replace it without affecting any other command.
> test.vim: refactor to use its own parse function

- autoload/go/test.vim
This change improves the way we compile a Go test. Previously we would
build a test binary to catch any build errors. A callback was then
responsible to delete the test binary after showing build errors (if
there were any).
This could be racy though, because if the tests lasts long and we quit
early, the callback to clean the binary file would never run. So we
would end up with artifacts in our working directory.
To fix the issue we're going to tell to the `go` tool to run a specific,
unique function. We're passing a unique identifier as a function name
(which is a randomly generated), i.e:
```
go test -run "F97CC94D-4414-41CF-A185-A077F645DF24"
testing: warning: no tests to run
PASS
ok  	demo	0.006s
```
This will cause the go tool to build
the test file and then try to run the test …
> test.vim: more efficient compiling of test files

- autoload/go/def.vim
It was using a deprecated flag.
Fixes #1312
> def: fix passing build tags to guru

- autoload/go/template.vim
- doc/vim-go.txt
- templates/hello_world_test.go
Use a template more appropriate for test files than templates/hello_world.go
when creating a test file in a directory with no Go files present. A new
option, g:go_template_test_file, allows users to specify their own template to
use.
Fixes #1216
> Use a different template for test files

- autoload/go/impl.vim
- autoload/go/package.vim
- autoload/go/path.vim
- autoload/go/util.vim
This improves vim-go by caching some of the most used commands and call paths.
> Improve caching for go env calls

- autoload/go/guru.vim
- autoload/go/jobcontrol.vim
- autoload/go/lint.vim
- autoload/go/package.vim
> package: improve import_path by using go list

- doc/vim-go.txt
`syntastic` can not use `errcheck` as a checker.
Sample vimrc:
```vim
let g:syntastic_go_checkers = ['golint', 'govet', 'errcheck']
```
Run `:SyntasticInfo`
```
Syntastic version: 3.8.0-56 (Vim 800, Darwin)
Info for filetype: go
...
Available checkers: go gofmt golint gometalinter govet
Currently enabled checkers: golint govet
```
When using `errcheck` with `syntastic`, you need to use `gometalinter` and specify `errcheck` as an option.
> Fix syntastic help

- autoload/go/test.vim
This has regressed after the refactor. Because I had this enabled
```
let g:go_echo_command_info = 0
```
I was not able to see it.
fixes #1324
> test: fix outputing message when test finishes

- autoload/go/coverage.vim
This allows things like ```:GoCoverage -run TestSpecific``` which allows you to see the exact coverage for a test/subtest.
It looks like this was the intent but may have been missed in https://github.com/fatih/vim-go/commit/dc8073386754bf5ca09a8dbe2bd9cc8886c61446
> coverage.vim: pass along arguments to coverage_job

- autoload/go/cmd.vim
This caches the results of `go build`, which makes it faster to execute
it on subsequent calls.
Fixes: #1329
> cmd: add -i flag to go build

- autoload/go/doc.vim
- doc/vim-go.txt
To control the maximum height of the window created by `:GoDoc` and `K`.
Also slightly tweak the documentation for `g:go_doc_keywordprg_enabled`, since
it doesn't actually use the `keywordprg` setting.
Fix some other small errors that [vimhelplint](https://github.com/machakann/vim-vimhelplint)
reported (wrong tag names, lines too long).
> Add g:go_doc_max_height setting

- .gitignore
- doc/vim-go.txt
- scripts/test.sh
There have been a few instances where this helped me catch some errors, for
example in #987 and #1335 where there were a few wrong tag names (e.g.
`|g:go_foo|` instead of `|'g:go_foo'|`).
> Add vimhelplint to Travis tests

- syntax/go.vim
The `{` here interferes with the folding in:
syn region      goBlock             start="{" end="}" transparent fold
I'm not sure if this is the best way to fix it; but it seems to work well as far
as I can see. I also tried mucking about with `contained` and such, but wasn't
able to get that to work.
Fixes #1282
> Match zero-width in goTypeConstructor

- autoload/go/textobj.vim
- doc/vim-go.txt
> textobj: include function variable for anonymous functions

- autoload/go/fmt.vim
silent! is skipping any error message when calling the command. However
if swapfile is enabled, the user is prompted to recover or edit the
file. If swapfile is enabled, the prompt is still called in background,
but the user doesn't see it. So the whole UI is blocked until you hit a
character (such as enter) which basically closes the hidden prompt.
By removing the `!` we still call the command silently, but at
least the user will see the message (such as swapfile prompts) in case
of errors.
fixes #1360
> fmt: fix blocking ui when swapfile is enabled

- autoload/go/list.vim
- doc/vim-go.txt
I have a workflow where I prefer to keep the quickfix/location window open during development.  vim-go likes to automatically close this window on successful operations (i.e., GoFmt, GoBuild, etc...).
This change adds a configuration property to prevent this from happening.  By default, the window automatically closes (current behaviour).  Users can specify 0 to allow the window to remain open.  Tested with a few of the basic operations, but let me know if you suspect any issues might arise.
> Added ability to keep the quickfix/location list window open

- syntax/go.vim
This is a regression from cfa9713. Previously the offset was needed since the
`{` was matched as well. Now we don't match the `{` the offset means the last
character of the type won't be matched.
Fixes #1357
> Don't add offset to goTypeConstructor.

- autoload/go/fmt.vim
- doc/vim-go.txt
Not sure why we were using location list, but I think quickfix is the
better way going forward as it's more known. The user can change the
behaviour back to locationlist if they want
let g:go_list_type = "locationlist"
Also fix fetching the correct list type setting (we were not checking it
at all)
fixes #1359
> fmt.vim: default to quickfix list for showing errors

- autoload/go/fmt.vim
> fmt.vim: fix cursor staying on the same line when goimports is used

- doc/vim-go.txt
- syntax/go.vim
This adds `foldmethod=syntax` folding for `import`, `var`, and `const` blocks.
I added a new `g:go_fold_enable` setting to selectively enable which regions get
folded. I find this useful personally as I only want to fold `import` blocks.
Future extension to this might be:
- `struct` and `interface`, to selectively fold `type foo struct { .. }` and
`type foo interface { .. }` definitions;
- `package`, to fold the package-level comment.
But that's another PR for another day ;-)
Fixes: #963
> Fold import, var, and const blocks

- autoload/go/fmt.vim
Save it before calling the formatter, and use the column argument
when setting the position after.
> Preserve cursor column through formatting

- autoload/go/doc.vim
When using `:GoGetDoc` without a `gogetdoc` binary it would still open the split
with the content `-1`. This fixes that.
An error message is not needed as `go#path#CheckBinPath` already shows that.
Related: #1346
> Don't show window if "gogetdoc" command isn't found

- autoload/go/def.vim
- autoload/go/doc.vim
- autoload/go/fmt.vim
- autoload/go/impl.vim
- autoload/go/keyify.vim
- autoload/go/lint.vim
- autoload/go/tags.vim
Fixes #1288, as well as a number of other commands.
There may be other places as well; this is just the result from a quick test
with my personal default settings. Since there are a lot of if/else branches
relating to jobs etc. it's kind of hard to test everything without a full audit.
It's perhaps a good idea to refactor some of this in a slightly more structured
way at some point: instead of passing strings we should pass a list which is
always escaped (like `os.Exec()`, Python's subprocess, etc.)
> Various fixes for paths and GOPATH with spaces

- autoload/go/tool.vim
- doc/vim-go.txt
- ftplugin/go/commands.vim
Instead of always using `GoFiles`, you can now use `:GoFiles TestGoFiles` to
list all test files. Or `:GoFiles GoFiles TestGoFiles` to list both all regular
Go files and test files.
Fixes #1346
> Allow specifying which filestypes to list for :GoFiles

- autoload/go/template.vim
When editing a new file:
vim newfile.go
Vim would show the results of the `:0r` command on startup:
"~/.vim/pack/plugins/start/vim-go/templates/hello_world.go" 7L, 67C
Instead of the default:
"newfile2.go" [New File]
This corrects that by adding running the `:0r` command with `silent`.
This would only occur if `go#tool#PackageName()` returns `-1`; the correct
message was already shown when a package is found.
There was an `echon` with a comment about removing the `[New File]` message, but
this seems like the wrong behaviour to me. Either way, it didn't work; maybe the
behaviour of `echon` subtly changed?
Fixes #1347
> Show correct message when editing a new file

- README.md
It took me a while to figure out the help tags had to be generated in order to use `:help vim-go`.
Making this more explicit might save some wandering souls a Google search :)
For most people `:helptags ALL` will do the right thing.
> Clarify :helpt prerequisite for using :help vim-go

- doc/vim-go.txt
Tested my wrapper script from #1222 and confirmed this works fine.
IMHO it's not worth making an option for this, as:
- very few people need it;
- is quite a bit of effort to implement;
- will make the code less readable;
- an easy workaround exists.
Fixes #1222
> Document how to use a different Go binary

- syntax/go.vim
This fixes two things:
- Exclude some more syntax matches for `goVar` and `goConst` to prevent
accidental matches inside these blocks. This fixes #1383.
- Change the end from `)` to `^\s*)$` so that it won't match function calls.
Previously in this example:
var (
foo = "bar"
bar = fun()
)
It would match on the first `)`; the closing `)` in `fun()`.
This still isn't perfect, as this is valid as well:
var (
foo = "bar"
bar = fun(
"arg",
"arg",
)
)
I'm not sure how to fix this case as well though...
> Fixes for folding var/const blocks

- autoload/go/def.vim
- autoload/go/job.vim
Instead of:
vim-go: SUCCESS
We now show:
vim-go: /usr/lib/go/src/strings/strings.go:340:6: defined here as func strings.Join
Showing the output of the command is optional; if we remove it we get the old
behaviour with the output of an `:edit` command:
"/usr/lib/go/src/strings/strings.go" [readonly] 777L, 20971C
Showing the command output seemed more useful to me personally though,
I moved the `custom_cb()` invocation after the message; this has no real effect
as far as I can see (it's used in only two places) and it allows us output
messages after the SUCCESS.
Fixes #1207
> Show message when using :GoDef and opening a new buffer

- syntax/go.vim
Otherwise they won't get highlighted and folding won't work correctly if an
`import` block contains a comment.
e.g.:
----
> Allow comments in import blocks

- autoload/go/def.vim
Setting switchbuf=usetab only is not enough since switchbuf only works for buffer related commands.
If mode is tab, I made it to use sbuf as cmd, instead of edit since edit will ignore the value of switbuf
> Issue 1396 go#def#tab fails if file is already open

- autoload/go/tags.vim
This adds two improvments for `:GoAddTags` and `:GoRemoveTags` commands.
1. Instead of creating a temporary file pass the modified content trough
stdin via the `-modified` flag
2. Show errors in quickfix list if gomodifytags couldn't process fields.
This depends on: https://github.com/fatih/gomodifytags/pull/23
> tags: use -modified flag and show errors

- CHANGELOG.md
- doc/vim-go.txt
- syntax/go.vim
This enables folding of the `// Package foo` and `/* Package foo` comments at
the top of files.
Ideally I'd also like to fold the `package ...` line in here, but this is kind
of hard to do... Maybe I'll take a look at that in a future date. For now, this
will do :-)
> Fold package-level comments

- autoload/go/term.vim
When triggering commands in term mode we enter insert mode. This is really frustrating. This fixes this behaviour and quits insert mode after entering it.
> term: exit insert mode

- autoload/go/impl.vim
- doc/vim-go.txt
- When using `:GoImpl` on `type foo struct{}` it would work, but with:
type foo struct{
}
or with a struct with fields, it would create the generated methods *inside*
the struct. Fixes #1077.
- Allow using `:GoImpl` on the `type` and `struct` parts too. Makes it a wee
bit easier to use ;-)
- Output would include extra newline, and error would include trailing newline
from shell command:
vim-go: invalid receiver: "} *}"<00>
- Small documentation fix.
> Some small :GoImpl improvements

- autoload/go/lint.vim
- tags
Execute `:GoMetalinter` in subdir, failed to parse filepath.
e.g.
Execute to `foo/bar.go`.
Now execute gometalinter in `foo/` dir.
So, result path will `bar.go` but want `foo/bar.go`
> Fix to fails of GoMetalinter result filepath in subdir. resolve #1413

- CHANGELOG.md
- autoload/go/def.vim
If I use `gd` on an identifier the filename for the new buffer is set to:
~/work/src/github.com/teamwork/desk/server/server.go
Instead of:
server/server.go
This makes it open the relative directory, making it behave as `:e
server/server.go`.
I *think* this change should be safe and will work for everyone? I'm not 100% of
that, though. Perhaps we should add a setting?
> Load buffers with :GoDef relative to cwd

- doc/vim-go.txt
- syntax/go.vim
This adds a match for variable definitions so that they can be highlighted using a color scheme. Variable definitions are the `foo` and `bar` in:
foo := ...
foo, bar := ...
> Vim syntax match for variable definitions

- doc/vim-go.txt
- syntax/go.vim
Improved fold syntax to include comments above, currently only working on funcs
> folding improvements

- autoload/unite/sources/decls.vim
- doc/vim-go.txt
[unite.vim][] is a powerful "listing & selecting" plugin that looks like ctrlp.vim.  I want to use `:GoDeclsDir` feature with unite.vim and have implemented it.
[unite.vim]: https://github.com/Shougo/unite.vim
It has almost like `:GoDeclsDir / :GoDecls`, but differs at some points below.
* `:Unite decls` has features for both `:GoDeclsDir` and `:GoDecls`, but the main target is `:GoDeclsDir` because `unite.vim` has already `:Unite outline` that is similar to `:GoDecls`.
* `:Unite decls` does not conflict with the existent `:GoDecls / :GoDeclsDir`, so both of them can be used if both unite.vim and ctrp.vim are installed.
The document about this on `vim-go.txt` is the one I am worrying about.  I placed it at the next of `:GoDeclsDir`, but does anyone have an idea to place somewhere better? …
> Add support for unite.vim about :GoDecls / :GoDeclsDir

- autoload/go/impl.vim
This fixes `:GoImpl` for cases when the interface package is in `vendor` or similar.  It depends on josharian/impl#18, which adds the `-dir` argument (`-dir` defaults to `$PWD` so hopefully the fallback won't be used much).
> GoImpl: support relative (vendor) imports

- CHANGELOG.md
@Carpetsmoker seems like the `#1234` syntax doesn't work. Do we have to use the URL link syntax? is this a bug?
> CHANGELOG.md: fix GH links syntax

- CHANGELOG.md
- autoload/go/package.vim
This didn't work at all on my system. Turned out the problem was that on
my system (Linux) some paths didn't have a trailing slash, so
`workspace` would be `/home/martin/gosrc`.
This makes sure that it always works, no matter if a trailing slash is
present or not.
Also `break` from the loop on the first match, so it selects the
*first* package found in GOPATH rather than the *last*. This is also how
imports in Go behave.
> Fix go#package#FromPath()

- autoload/go/guru.vim
There is a race condition in `async_guru` in which not all messages from
a `guru` call are displayed:
1. An async `guru` call is started.
2. Lines streamed from `guru` are appended to a message list in
`callback()`.
3. The `guru` process ends, `exit_cb()` is called, and the list of
messages is processed for display.
4. The rest of the lines from `guru` are appended to the message list.
Note that `callback` may still be called after `exit_cb`, as noted in
`:help exit_cb`:
"exit_cb": handler	…
Note that data can be buffered,
callbacks may still be called after
the process ends.
This race was recently exposed by [Vim v8.0.1073][vim], which avoids a
redraw after statusline evaluation changes a highlight. Since vim-go
modifies the goStatusLineColor highlight definition on async calls, the …
> Parse messages from guru on close_cb, not exit_cb

- autoload/go/cmd.vim
- autoload/go/coverage.vim
- autoload/go/fmt.vim
- autoload/go/guru.vim
- autoload/go/job.vim
- autoload/go/jobcontrol.vim
- autoload/go/lint.vim
- autoload/go/list.vim
- autoload/go/rename.vim
- autoload/go/tags.vim
- autoload/go/term.vim
- autoload/go/test.vim
- doc/vim-go.txt
Add a new setting, `g:go_list_type_commands`: a dictionary
whose entries allows users to customize whether to use the quickfix list
or the location list for each command. The dictionary does not require
an entry for every command; only those the user wants to specify.
When g:go_list_type is set and g:go_list_type_commands contains an entry
for a command, go:go_list_type_commands takes precedence.
I'm not totally happy with the keys for the commands in the `g:go_list_type_commands` dictionary. Currently the entries map very closely to the commands (e.g. `:GoBuild`), providing an easy to understand set of keys for most users. Unfortunately, the `GoModifyTags` entry applies to both `:GoRemoveTags` and `:GoAddTags` commands, because the way those two commands are implemented makes it a little …
> support for customizable lists types

- autoload/go/jobcontrol.vim
Fixes #1444 
@reireias can you give this a try? I don't have neovim installed, but I'll install and test it tonight if you're unable to get to it.
> fix arguments to jobcontrol#s:spawn

- CHANGELOG.md
- ftplugin/gohtmltmpl.vim
This will make `%` with the `matchit` plugin loaded work as expected,
and also adds some other features.
> Load ftplugin/html.vim for gohtmltmpl

- autoload/go/cmd.vim
- autoload/go/fmt.vim
- autoload/go/guru.vim
- autoload/go/job.vim
- autoload/go/jobcontrol.vim
- autoload/go/lint.vim
- autoload/go/list.vim
- autoload/go/rename.vim
- autoload/go/tags.vim
- autoload/go/term.vim
- autoload/go/test.vim
Refactor go#list#Type for maintainability. Instead of having the
supported keys (both internally and externally supported) spread
throughout the code, use a single map that contains the keys and their
defaults in autoload/go/list.vim.
Refactor go#list#Type so that it is aware of the map of default values
and does not need its second parameter.
After refactoring, I realized that the default list type for `GoAddTags` and `GoRemoveTags` should be `locationlist` instead of `quickfix`, so I made that change, too.
> Consolidate list type command keys

- CHANGELOG.md
- autoload/go/cmd.vim
There was a stray `go#util#Shelllist()` in there. As near as I can tell
this isn't needed at all. Probably a left-over from some earlier
version?
Also move the non-async code in an `else`, I think this makes it a lot
clearer which code path does what. The two early returns were kinda
confusing.
Tested with Vim 8, 7.4, and Neovim, and seems to work well.
Fixes #1404
> Fix :GoBuild shell escaping

- autoload/go/list.vim
> Fix syntax for `s:default_list_type_commands`

- doc/vim-go.txt
- syntax/go.vim
Currently `g:go_highlight_variable_declarations` allows to highlight variables with the short variable declaration syntax. This change adds the possibility to highlight variables assigned with the standard assignment operator e.g.:
```go
a, b = foo()
struct.field, _ = bar()
```
It introduces `g:go_highlight_variable_assignments` to allow enabling/disabling the behaviour.
> Variable assignments syntax highlighting

- CHANGELOG.md
- autoload/go/job.vim
- autoload/go/rename.vim
- autoload/go/test.vim
- autoload/go/util.vim
Unlike `:echo`, `:echom` is rather stupid. It will display a newline as
`^@` or `<00>` and tabs as `^I` or `<09>` (depending on the `display`
setting).
This some messages display nicer, for example `:GoBuild --` looked
rather confusing before, and looks as expected now.
Before:
After:
Needs some more testing (Vim 7.4, Neovim), but seems to work well.
This fixes some – but not all – of #1429.
> Show multiline errors

- CHANGELOG.md
- autoload/go/doc.vim
- autoload/go/fillstruct.vim
- autoload/go/guru.vim
- autoload/go/util.vim
- doc/vim-go.txt
- ftplugin/go/commands.vim
- plugin/go.vim
Just the bare basics; fixes #1425.
> Implement :GoFillStruct

- syntax/go.vim
Add regular expression branches so that all assignment operators will be
highlighted (e.g. +=, |=, et al.).
Add a match for character other than '=' at the end of the goVarAssign
match expression so that equality comparision (i.e. '==') won't match.
> teach goVarAssign about all assignment operators

- CHANGELOG.md
- autoload/fzf/decls.vim
- autoload/go/decls.vim
- doc/vim-go.txt
- ftplugin/go/commands.vim
Revisiting #976.
This introduces a new configuration option (``g:go_decls_mode``). It's still missing documentation, but I wanted to open the PR anyway so I can get feedback on the implementation before moving forward with the documentation.
> Support fzf on GoDecls[Dir]

- doc/vim-go.txt
- syntax/go.vim
Also moves all of this to a new section. Fix #1403
> Documentation for syntax highlighting

- autoload/go/fillstruct.vim
- autoload/go/path.vim
- autoload/go/util.vim
This is intended as a replacement for `go#util#System()`. The main
difference is that this will accept a list instead of a string as the
command, and that every item in the list will be automatically
shell-escaped.
This means you can just do:
echo go#util#Exec(['printf', 'look "quotes" and spaces and stuff!'])
and not worry about escaping and stuff.
This approach makes much more sense IMHO, and is also what Go's os/exec
and Python subprocess do. It's especially useful with the jobs API,
since that *doesn't* need escaping, so it makes things easier all round.
Vim still needs to use the shell unfortunately; it can't run programs
directly.
I added a new function instead of modifying `System()` so we can migrate
slowly and carefully; double escaping will break stuff! I just converted …
> Add go#util#Exec()

- autoload/go/guru.vim
- doc/vim-go.txt
This clarifies the documentation the guru scope in an FAQ
entry. It also mentions this page when using commands that require the
guru scope.
There is no real way to guess what the user intended, should it be
`github.com/user/pkg`, or `github.com/user/pkg/subpkg`, or something
else?
I think this is a good way to fix #1037.
> Clarify the documentation for the guru scope.

- CHANGELOG.md
- doc/vim-go.txt
- plugin/go.vim
- Support arguments; fixes #1438
- Add `-ldflags -H=windowsgui` when installing `gocode` on Windows; fixes #1454
> Allow arguments for :Go{Install,Update}Binaries

- autoload/go/util.vim
It's "only" a year old (7.4.2071), and older Vim 7.4 versions don't have
it.
Fixes #1477
> Don't use `v:t_list`.

- autoload/fzf/decls.vim
> Fix #1484  GoDecls break when motion returns empty

- autoload/go/fmt.vim
> ensure fmt list gets closed when title cannot be checked

- autoload/go/util.vim
There was a bug on `GoBuild` with vim74. The variable l:msg in util echo function is a string even after calling split() that causes a crash on the map() call.
Issue #1483
> Fix util echo function: ensure l:msg is a list after split()

- README.md
- doc/vim-go.txt
Edit the INTRO and INSTALL sections of the documentation. Edits mostly
consist of rewording some sentences and paragraphs to read more
naturally.
Consistently capitalize vim-go, even if it's the first word in a
sentence. This might not seem right to you at first, but think about how
other proper nouns that begin with a lower case letter (e.g.  iPhone)
are capitalized when used as the the first word in a sentence.
Make analogous edits to README.md
> edit documentation

- autoload/go/doc.vim
Hello. First of all sorry for my english.
I am encounter an issue.
The steps to recreate it:
1. Call `:GoDoc os`
2. Move GoDoc window to the right
3. And then call `:GoDoc io`
Result looks like this:
> [GoDoc] Fix: don not resize GoDoc window if its still visible

- doc/vim-go.txt
- plugin/go.vim
Correct references to 'g:go_bin_path' in :GoInstallBinaries and
:GoUpateBinaries documentation, and make the references links to
documentation for 'g:go_bin_path'.
Clarify that :GoInstallBinaries and :GoUpdateBinaries do not take
multiple lists (they only take single lists) by making their
documentation congruent with other commands' documentation.
Edit the description comment GoInstallBinaries() for completeness.
Document that :GoUpdateBinaries respects 'g:go_get_update'.
> edit help file and function description

- .github/ISSUE_TEMPLATE.md
Edit the issue template to more clearly walk issue submitters through
the process of providing a good report.
* Clearly prompt the submitter for what they did, what they expeted, and
what they saw.
* Added an entry to the issue template configuration section to prompt
submitters for their operating system.
* Added a parenthetical to let submitters know how to get their current
Go version.
* Moved the vimrc prompt to the end of the configuration list since it
is usually larger and spans multiple lines.
> edit issue template

- autoload/go/play.vim
- autoload/go/tool.vim
- autoload/go/util.vim
- doc/vim-go.txt
It never mentioned that you need to use `%URL%` or that you're expected
to return the shell yourself.
While I'm here also add `chromium` to list (the binary for Chrome proper
seems to differ a lot per Linux distro) and move the macOS detection to
a function.
Fixes #1487
> Clarify documentation for g:go_play_browser_command

- autoload/go/rename.vim
- autoload/go/util.vim
- doc/vim-go.txt
- ftplugin/go/commands.vim
1. Repurpose `g:go_gorename_prefill` to be an expression, which can
transform the value that is pre-filled to the most common forms.
The default is to use camelCase when the identifiers starts with a
lowercase letter, and CamelCase when it starts with an uppercase
letter, which sounds like a reasonable guess to me.
2. Add completion support, so you can use `:GoRename <Tab>` to get the
most common options.
Both of these changes make it a bit easier/faster to use, especially if
you need to rename a bunch of identifiers in a project that doesn't
follow Go standards (like I had to do last week).
> Better prefill and completion for :GoRename

- autoload/go/test.vim
Normalize message output from autoload/go/test.vim to use the
go#util#Echo* functions instead of replicating their functionality.
Use the same messages for Vim 7.4 and 8.0.
> normalize message output

- autoload/go/test.vim
Do not try to run a non-existent test for :GoTestCompile. Instead,
compile tests to a temporary file with `go test -c` in order to avoid
problems that may be caused by runtime errors in an init function when
trying to run a non-existent test.
To avoid the problems that 21376e689d6b701b4367cf121da4cfcf17e5fa19
resolved, this change relies on Vim's managing of the temporary
directory instead.
Fixes #1515
> do not try to run tests for :GoTestCompile

- CHANGELOG.md
- autoload/go/path.vim
- doc/vim-go.txt
Disable g:go_autodetect_gopath by default since first class support for
vendoring was enabled in Go by default a year and a half ago in Go 1.6
and most vendoring tools use it. At this point, there is a greatly
reduced need to detect whether the old method used by Godep and gb is in
effect.
> disable g:go_autodetect_gopath by default

- CHANGELOG.md
- plugin/go.vim
This shows a warning when people use an older Vim version. You can still set
`g:go_no_version_warning` to override this, if people really want to continue. I
don't think we need to bother documenting that setting in the help page.
The version 7.4.1689 was chosen because that's what the latest Ubuntu LTS
(16.04) uses, which seems like a reasonable choice. I don't mind using an older
version though.
> Display warning when people use an older Vim

- CHANGELOG.md
- gosnippets/UltiSnips/go.snippets
The gpl snippet failed to interpolate the current year.
> Fix UltiSnips gpl snippet

- .editorconfig
- Makefile
- scripts/docker-test
To make running tests in Docker easier.
This really an alternative/fix to #1549.
> Add scripts/docker-test

- autoload/go/lint.vim
Previously we'd lint test files. In the recent PR
alecthomas/gometalinter#377, gometalinter stopped asking errcheck to
lint tests. This change makes us again lint test files which I think is
sensible.
> Pass --tests flag to gometalinter so that we lint test files

- autoload/go/test.vim
I have a test that uses build tags: `// +build integration`.
I found I wasn't able to build it in vim, so I added this. Seems correct to me.
> Make :GoTestCompile respect build tags

- autoload/go/tool.vim
- autoload/go/tool_test.vim
> eliminate errors trying to run a command in a directory that does not exist

- autoload/go/test.vim
* Use stricter regular expression to correctly identify potential file
references in test output. When `go test` outputs a test failure file
location, the file is preceded with at least one tab. If there is
leading space on the line, then it's a subtest that failed. Use that
to more accurately disregard lines that will not refer to files.
* Preserve multi-line test failure output by similarly checking for at
least one tab ahead of the output.
* Preserve output that seemingly *should* refer to a file, but for
whatever does not, but don't make it a file reference for the purposes
of quickfix and location lists.
* Preserve all lines of stack traces.
* Correctly recognize file locations in stack traces.
Fixes #1179 and at least partially addresses #1493.
> improve test output handling

- autoload/go/impl.vim
- autoload/go/impl_test.vim
- autoload/gotest.vim
- ftplugin/go/commands.vim
Fixes #1554
The problem is that `:GoImpl somethingInvalid` would set
`v:shell_error`, and on the next `:GoImpl <Tab>` the `go#util#env()`
call in `s:root_dirs()` would use the cache, so the `v:shell_error` is
"stuck".
Fix it by not checking this here; `go#util#env()` already shows an error
so that should be fine.
Long-term fix is to use `go#util#Exec()` everywhere which returns
`v:shell_error` instead of relying on a global value.
While I'm here also add a basic test and use `Exec()` in a few places.
> Fix :GoImpl completion

- autoload/go/fmt.vim
This should ensure that it breaks less often. The downside is that it's
a bit slower, but it still seems plenty fast enough on my system even
with large files.
Fixes #1447
> Sync syntax from start after gofmt

- scripts/runtest.vim
- scripts/test
Deals better with some errors, add some commandline flags, and improve
output.
It will now also run tests from all directories, instead of the autoload
directory. I wanted to add a test for #1525, and putting it in
`autoload/go/` seemed wrong to me.
Would also be nice to be able to run just one test with e.g.
`-r tags_test.vim:Test_Foo`. I'll add that when I need it I guess.
Regular:
[~/.vim/pack/plugins/start/vim-go](master)% ./scripts/test vim-8.0
ok   tags_test.vim              0.146627s / 2 tests
ok   fillstruct_test.vim        0.685770s / 1 tests
ok   tool_test.vim              0.083538s / 2 tests
ok   def_test.vim               0.018329s / 2 tests
ok   fmt_test.vim               0.023622s / 3 tests
All tests PASSED
Test failure:
[~/.vim/pack/plugins/start/vim-go](master)% …
> Some small test running improvements

- autoload/go/alternate.vim
- autoload/go/alternate_test.vim
- autoload/go/util.vim
- autoload/gotest.vim
- scripts/runtest.vim
- scripts/test
Use the `:sbuffer` command when it's already loaded. This is especially
useful if switchbuf is set to useopen or usetab.
Otherwise setting g:go_alternate_mode to `split` or `tabe` will just
keep on creating new windows or tabs.
This also fixes a bug where paths with e.g. a space didn't work
correctly.
Also add a test for go#alternate#Switch() and a few help for tests. If
`g:go_running_tests` is set, `go#util#Echo*` will record messages in
`g:go_messages` so we can easily access it from tests.
> Use :sbuffer in :GoAlternate

- Dockerfile
Move RUN instruction to install vim-vint so that it will be in $PATH.
By moving the instruction to before the USER instruction, vim-vint will
be installed to /usr/local/bin instead of /vim-go/.local/bin;
$HOME/.local/bin is not in $PATH...
Also upgrade to Go 1.9.2.
> fix vim-vint installation

- .coveragerc
- .gitignore
- .travis.yml
- scripts/run-vim
- scripts/test
https://github.com/Vimjas/covimerage
Seems to work well: https://github.com/Carpetsmoker/vim-go/pull/3
You'll need to enable codecov.io on vim-go to get this to work here too @fatih.
Also thank you @blueyed for covimerage.
> Code coverage reports with covimerage

- autoload/go/doc.vim
- doc/vim-go.txt
Useful to use internal, private installations.
> doc: make godoc instance configurable

- Makefile
- scripts/test
* Use a Make variable, VIMS, to specify which versions of Vim should be
installed and tested.
* Include Vim version in test report to make correlation easier.
With these two changes, it's much easier to test only a single version
of Vim by running something like
docker run -e VIMS=vim-8.0 -v $PWD:/vim-go vim-go-test
These changes are also included in #1583 , but it's taking me a little longer to get those done than I expected, and I've wanted the changes a couple of times while working on other things, too. Since it's separable, I figured I'd separate it :-)
> improve testing story

- .gitignore
- CHANGELOG.md
- doc/vim-go.txt
- rplugin/python3/denite/source/decls.py
[denite.nvim][] is the successor of [unite.vim][].  This PR enables `:GoDecls` & `:GoDeclsDir` features by denite as same as unite in #1391.
[denite.nvim]: https://github.com/Shougo/denite.nvim
[unite.vim]: https://github.com/Shougo/unite.vim
```vim
" available below as same as :Unite decls
:Denite decls
:Denite decls:foo.go
:Denite decls:foo/bar
```
denite is written for NeoVim / Vim 8 and it uses more progressive features than unite.  The expansions of denite must be written in Python3.
| `:Denite decls` |
|---|
| <img width="766" alt="2017-12-07 23 33 25" src="https://user-images.githubusercontent.com/1239245/33720448-4fd36984-dba7-11e7-8074-e40c9495ee57.png"> |
> Add support for denite.nvim about :GoDecls / :GoDeclsDir

- CHANGELOG.md
- autoload/go/fmt.vim
A lot of scripts filter files based on their name to make sure they
operate only on the appropriate content. By appending a Go file type to
a temporary file when running a formatter, we add support for a broader
range of Go formating tools.
Fixes #208
> Append Go file type when creating temporary file

- CHANGELOG.md
- plugin/go.vim
Was missing a space in composing the command, so this would get run:
go get -v -u -ldflags -H=windowsgui"github.com/nsf/gocode"
> Fix installing `gocode` on Windows

- autoload/go/fillstruct.vim
- autoload/go/fillstruct_test.vim
- autoload/gotest.vim
This way the cursor doesn't need to be exactly on the struct.
If multiple structs are found it will still prefer the one under the
cursor. Otherwise it will expand both.
Needs https://github.com/davidrjenni/reftools/pull/8 (tests will fail before that's merged)
> Implement -line for fillstruct

- .dockerignore
- scripts/test
Neovim closes stdin, so make sure to give it a stdin that is not
inherited from the parent process, because the parent process is reading
from its stdin...
Add .local/ to the list of ignored patterns for Docker so that Neovim
does not encounter errors trying to read the ShaDa file when trying to
build the Docker image after having run the Docker container with the
cwd mounted into the container at /vim-go.
> Make sure all tests run in Neovim

- CHANGELOG.md
- autoload/go/template.vim
Previously `vim ~/go/src/newdir/main.go` would result in:
"~/go/src/newdir/main.go" [New DIRECTORY]
Error detected while processing function <SNR>56_template_autocreate[3]..go#template#create:
line    6:
E344: Can't find directory "/home/martin/go/src/newdir" in cdpath
E472: Command failed
With this change this gets treated like a directory which isn't a Go
package yet.
> Fix go#template#create() for directories that don't exist yet

- autoload/go/term.vim
1. Since `a:mode` will always be "", it's better to use `mode`. When user set `let g:go_term_mode = "split"`, it could be supported.
2. Use `=~` instead `==` to cover case like `botright split`.
3. Window switch should be done after all terminal buffer command finished.
> improve neovim support

- doc/vim-go.txt
Now [deoplete.nvim][] supports Vim 8 in addition to NeoVim.
[deoplete.nvim]: https://github.com/Shougo/deoplete.nvim
> Add note for deoplete on Vim 8

- autoload/go/test.vim
Fixes #1619
Adds go_test_timeout support to GoTestFunc
> Fix: GoTestFunc dont respect go_test_timeout

- autoload/go/doc.vim
The user's configured "go_doc_url" variable should still work correctly in the case when the "gogetdoc" command isn't installed.
> add additional godoc url configuration

- autoload/go/test-fixtures/test/src/timeout/timeout_test.go
- autoload/go/test.vim
- autoload/go/test_test.vim
Do not treat a panic caused by a test timeout as an error that occurred
within a test's callstack. When go test panics due to a test timeout,
the running goroutine's stacktrace only contains entries for the
standard library, and there is one goroutine whose stacktrace contains
entries for the standard library and the test binary. None of the other
goroutines should be considered to contain an error, either, because the
panic was not due to any code executing within those goroutines' stacks.
Therefore, treat panics caused by a test timeout as an error without a
file location.
> fix quickfix list when test duration exceeds timeout

- CHANGELOG.md
- syntax/go.vim
Per the go docs for the fmt package, there is a bracket expression that is supported in format strings. 
For example,
`
fmt.Sprintf("%[2]d %[1]d\n", 11, 22)
fmt.Sprintf("%[3]*.[2]*[1]f", 12.0, 2, 6)
fmt.Sprintf("%d %d %#[1]x %#x", 16, 17)
`
Should all be valid syntax highlighted format strings.
> support syntax highlighting for bracketed expression in fmt string

- gosnippets/snippets/go.snip
Change same abbr according to contents.
> Improve snippets abbr

- autoload/go/test-fixtures/test/src/showname/showname_test.go
- autoload/go/test.vim
- autoload/go/test_test.vim
Respect the current value of g:go_test_show_name on :GoTest runs after
the first one by invalidating the cached errorformat value when the
g:go_test_show_name value is not the same as it was when the errorformat
value was last cached.
Only show the test name for failed tests instead of including the
'--- FAIL: ' prefix and the duration suffix when g:go_test_show_name=1.
Resolve a TODO item in the test errorformat so that the regular
expression used for test errorformat values is more precise.
Remove a bit of testing code that is no longer needed; it was probably
rendered obsolete with some recent changes to how the errorformat value
is created.
> respect a changed g:go_test_show_name

- autoload/go/lint.vim
- autoload/go/lint_test.vim
- autoload/go/test-fixtures/lint/src/foo/foo.go
- autoload/go/test-fixtures/lint/src/lint/lint.go
- autoload/go/test-fixtures/lint/src/lint/quux.go
- autoload/go/test_test.vim
- autoload/gotest.vim
Make sure linter errors for the file being saved are shown in vim74 and
nvim.
Make sure only linter errors for the file being saved are shown in vim8.
Previously, all linter errors for all files in the current file's
directory were being shown.
Make sure gometalinter is run on the given directories when arguments 
are given to `:GoMetaLinter`.
Fixes #1623
> Fix metalinter problems

- doc/vim-go.txt
- syntax/go.vim
Separating method calls from calls on a package is not easy with the
current regexp based syntax highlighting. Is `fmt.Println` a method call
or function call?
This fixes #1500 by clarifying what the setting is supposed to do. I
think this makes sense, because people who want to highlight function
declarations probably want to do this for both functions and methods,
and people who want to highlight function calls want to do this for
functions and methods, too.
> Rename go_highlight_methods to go_highlight_function_calls

- ftdetect/gofiletype.vim
When sourcing `ftdetect/*.vim` (in `$VIMRUNTIME/filetype.vim`), `augroup filetypedetect` is already set.
Thus using `augroup` in ftdetect script, autocmds in gofiletype.vim and in other ftdetect scripts sourced after gofiletype.vim do not belong to `augroup filetypedetect`.
This makes some behaviors about filetype (e.g. `:filetype off`) broken.
> Fix ftdetect

- autoload/go/lint.vim
- autoload/go/lint_test.vim
- doc/vim-go.txt
Use gometalinter's `--disable` option instead of its `--exclude` to
disable linters specified in `g:go_metalinter_excludes`; `--exclude` is
to exclude files, `--disable` is for disabling linters.
Rename `g:go_metalinter_excludes` to `g:go_metalinter_disabled` to more
accurately reflect its purpose in its name and so that it's symmetric
with `g:go_metalinter_enabled`.
> Fix handling and change name of g:go_metalinter_excludes

- autoload/go/path.vim
Reduce the visibility of some functions that are never called outside of the script in which they are declared.
> Reduce path function scope

- autoload/go/lint.vim
Redraw the screen when gometalinter is called automatically after saving
a file (i.e.  g:go_metalinter_autosave = 1), so that the user will not
be prompted to press enter.
Fixes #1617
> do not prompt user to press enter after saving

- autoload/go/cmd.vim
- autoload/go/coverage.vim
- autoload/go/def.vim
- autoload/go/guru.vim
- autoload/go/job.vim
- autoload/go/lint.vim
- autoload/go/rename.vim
- autoload/go/test.vim
Eliminate race conditions that were possible in vim8 job handling.
Most jobs were only handling the `exit_cb` handler for job options. To make sure that all messages are handled, `close_cb` has to be hooked up and coordinated with `exit_cb`, because there is no guarantee about which order they will be called in.
Refactor `autoload/go/job.vim` to call the caller-provided callbacks only after the job has exited _and_ channel has been closed so that the actual exit status and all messages can be provided. I also took this opportunity to clean up and simplify `go#job#Spawn` so that there's only one callback called when the job completes instead of two and so that the return value only exposes the callbacks that are needed by the caller.
Refactor `autoload/go/guru.vim` to account for the fact …
> Fix async race

- autoload/go/cmd.vim
Vim docs say that autowriteall implies autowrite, so make sure that
go#cmd#autowrite() has the same behavior when only one of either
autowrite or autowriteall is set.
> handle autowriteall the same as autowrite

- autoload/go/lint.vim
- autoload/go/lint_test.vim
- autoload/go/list.vim
- doc/vim-go.txt
gometalinter is used in two distinct cases. When run using
:GoMetaLinter, all of its output is used. When run automatically on save
(e.g. g:go_metalinter_autosave=1), only its output that applies to the
current buffer is used. In that case, it makes sense to show its
messages in the location list without forcing the user to also use the
location list when the user executes :GoMetaLinter.
Therefore, add a new key to g:go_list_type_commands,
GoMetaLinterAutoSave, with a default value of locationlist and modify
go#lint#Gometa to distinguish between the two cases.
Fixes #1644
> separate gometalinter error list use cases

- syntax/go.vim
If a package comment contained a line starting with "package", then it terminated the package comment. Ensure that "package" is preceded with a comment block terminator to fix the highlighting.
Before and after:
> Ensure that goPackageComment region ends after comment.

- autoload/go/guru.vim
- autoload/go/job.vim
- autoload/go/lint.vim
- autoload/go/rename.vim
- autoload/go/test.vim
Refactor vim8 async jobs to use dictionaries to maintain job state instead of closures so that multiple running jobs don't close over the same variable.
Fixes #1681
> use dictionaries instead of closures to maintain job state

- README.md
- autoload/go/debug.vim
- autoload/go/util.vim
- doc/vim-go.txt
- ftplugin/go/commands.vim
- plugin/go.vim
- syntax/godebugoutput.vim
- syntax/godebugstacktrace.vim
- syntax/godebugvariables.vim
Hi, I added debugger. Do you have interesting this?
> add GoDebug

- CHANGELOG.md
- ftplugin/go/snippets.vim
path separator on Windows should be ';' not ':'
> fix path separator of minisnip_dir

- autoload/go/template.vim
vim-go doesn't keep the previous value of alternate-file register
while reading templates. As a result, you will not be able to go back
to the buffer you were editing.
Suppose you have a directory structure like:
```
.
├── cmd/
│   └── bar/
└── foo.go
```
And you are editing a file in vim:
```$ vim foo.go```
and then you decided to create a new go file like:
```:e cmd/bar/bar.go```
Once you finished with 'bar.go', you hit CTRL-^ to return to the
previously edited file (foo.go), but you unexpectedly end up in
```$RTP/vim-go/templates/hello_world.go```.
This PR addresses this issue by prefixing the :read command in
```go#template#create()``` with :keepalt.
> Keep current alternate-file name while reading templates

- gosnippets/UltiSnips/go.snippets
- gosnippets/snippets/go.snip
Hi! I have added an extra snippet to use the 'fe' combination to autocomplete the fmt.Errorf(...) in UltiSnips.
> add  fmt.Errorf() snippet in UltiSnips

- autoload/go/guru.vim
Previously, enabling auto_same_ids and auto_type_info in neovim on large
go projects resulted in a noticeable UI pause while neovim was waiting
for the guru process to produce output. This was not a problem in Vim8
since vim-go already uses the job_start async api for Vim8.
This commit enables transparent use of neovim jobstart api to accomplish
the same async behavior in neovim. This commit also fixes a bug where
enabling auto_same_ids prevented :GoImplements from correctly popping up
the location list.
> neovim: invoke guru functions via async api

- autoload/go/debug.vim
Fixes #1691
1. Run `command GoDebugBreakpoint` after making it available again.
2. Clear `message` too in `s:clearState()`, so that `s:isActive()` works
correct.
> Make sure :GoDebugBreakpoint works after :GoDebugStop

- autoload/go/cmd.vim
We don't need this hack anymore to speed up building.
> cmd: go 1.10 maintains a build cache now

- autoload/go/cmd_test.vim
- autoload/go/job.vim
- autoload/go/jobcontrol.vim
- autoload/go/lint.vim
- autoload/go/lint_test.vim
- autoload/go/list.vim
- autoload/go/test-fixtures/cmd/bad.go
- autoload/go/test-fixtures/lint/src/vet/vet.go
Errors from `:GoBuild` were including the column number in the quickfix error's `text` message instead of it parsing it into in the quick fix error's `col` field, because `errorformat` wasn't being using used parse the errors when `go build` was run asynchronously.
This PR uses `go#list#Parse` to parse the errors so that the result in vim8 and Neovim is the same as it is in vim7.4.
While I was at it, I added a test for `:GoVet` and modified it to also use `go#list#Parse`.
> Fix go build error parse

- autoload/go/job.vim
- autoload/go/term.vim
* Explicitly close the terminal window instead of assuming the terminal
window is the current window and closing that.
* Eliminate the outstanding job list in favor of using a more object
oriented like approach.
* Make sure the correct location list gets used instead of assuming that
the current window is the window whose location list should be used.
Fixes #1720
> Fix various race conditions when using terminal windows

- autoload/go/term.vim
Make sure the correct location list is cleaned when terminal mode has no
output.
> close the correct location list

- autoload/go/fmt.vim
- autoload/go/job.vim
- autoload/go/jobcontrol.vim
- autoload/go/lint.vim
- autoload/go/list.vim
- autoload/go/rename.vim
- autoload/go/term.vim
- autoload/go/test.vim
After cleaning a list, there is no need to show the list anymore. That's
why we call `Window()` to invoke the close function. Remove all
`Window()` calls and make Clean() more useful to avoid adding the second
line. There is no single `Clean()` call independently, so it makes sense
to change the meaning
> list: make Clean() more useful

- autoload/go/package.vim
Cache the results of import path lookups so that go list doesn't have to
be run every time linting is run or go#guru#Sameids() is run, because go
list can take a noticeably long time to return results and has to be
executed synchronously for all of its current use cases.
This further reduces the likelihood that characters will be rendered at
the cursor position when in normal mode.
> cache import path lookups results

- autoload/go/term.vim
- autoload/go/term_test.vim
- autoload/go/test-fixtures/term/term.go
* Make sure that behavior is consistent when `g:go_term_enabled=1` regardless of the value of the `splitright` option.
* Remove the startinsert and stopinsert pair; they cancel each other out
and are unnecessary.
* remove superfluous stderr callback.
> Fix term enabled behavior

- autoload/go/coverage.vim
- autoload/go/util.vim
Do not redraw before showing all messages; only progress messages will
cause a redraw.
Convert the progress message in `go#coverage#Buffer` to a call to
`go#util#EchoProgress`.
> redraw before showing progress message only

- autoload/go/debug.vim
- autoload/go/textobj.vim
- doc/vim-go.txt
- ftplugin/go/commands.vim
This fixes the two issues reported in #1690.
The first issue is fixed by cd-ing in to directory before debugging
test files. This is also what `go test` does ad seems to work well
in my testing.
---
The second issue is fixed by adding `:GoDebugTest`:
Imagine I'm editing `a_test.go`, which is failing. To investigate I want
to add a breakpoint in a function in `a.go`. The current procedure for
that is something like:
- `:e a.go`
- `:GoDebugBreakpoint`
- `:e a_test.go`
- `:GoDebugStart`
- `<F5>`
- Buffer will switch back to `a.go`
The `:e_test.go` is needed because the only way to run `dlv test`
instead of `dlv debug` is to have the current buffer end in `_test.go`.
I think this is rather awkward, so add `:GoDebugTest` instead of trying
to guess what the users wants so you now can do:
- `:e …
> Add :GoDebugTest

- autoload/go/debug.vim
Show stderr as error, not progress.
It *still* only shows the last time, but that's the nature of outputting
stuff in a job callback: you don't get the "hit ENTER" prompt (which in
this case is *wanted*). I don't know if there is any way to fix that
(it's a problem we have in several commands)?
We can probably populate the quickfix like we do with `:GoInstall` and
such, but that's a PR for another day.
See #1742
> Show debug errors as errors and not progress

- autoload/go/debug.vim
Fixes #1744. Second part is that it should probably warn/error
if `autowrite` is disabled and there are unsaved changes, but that
is a more general issue that also applies to other commands.
> Write buffer before running GoDebugStart

- autoload/go/job.vim
- autoload/go/jobcontrol.vim
- autoload/go/lint.vim
- autoload/go/test.vim
Use window ids instead of window numbers to select windows in all async
job callbacks so that the correct window is selected even when the user
modifies the window layout between when the job is started and when the
callback is executed.
> use window id instead of number in all async jobs

- README.md
- doc/vim-go.txt
I use `vim-plug` to manage my Vim plugins and I think we can include the post-update hook to the docs.
> Adds vim-plug post-update hook to documentation

- .travis.yml
- autoload/go/guru_test.vim
- autoload/go/lint_test.vim
- autoload/go/test_test.vim
- scripts/runtest.vim
Also set `let g:go_echo_command_info = 0` and add some `silent`s to make
normal (non-failing) test output less noisy.
> Use Go 1.10 in tests

- CHANGELOG.md
- autoload/go/cmd.vim
- autoload/go/config.vim
- autoload/go/coverage.vim
- autoload/go/def.vim
- autoload/go/doc.vim
- autoload/go/fillstruct.vim
- autoload/go/guru.vim
- autoload/go/keyify.vim
- autoload/go/rename.vim
- autoload/go/test.vim
- doc/vim-go.txt
- scripts/install-vim
> Add build tags to many commands

- gosnippets/UltiSnips/go.snippets
Suggestion for a more robust errn, snippet. This arose by the need to format the error message at times. For example
if err != nil {
return nil, fmt.Errorf("some context: %s", err)
}
The snippet will allow you to tabstop to the err keyword for replacement.
> add tabstop on err

- .github/ISSUE_TEMPLATE.md
- autoload/go/issue.vim
- doc/vim-go.txt
- ftplugin/go/commands.vim
Add a new command, `:GoIssue`, to make it easier for users to open bug reports with most system information filled in.
I'm not completely happy with the name of the command and am open to other suggestions. I thought about using `:GoBug`, but that may lead people to believe that it's `go bug`. `:VimGoBug` also doesn't seem right, because none of the other commands start with `VimGo` :thinking:.
> Add :GoIssue to open bug reports on GitHub for vim-go

- autoload/ctrlp/decls.vim
- autoload/fzf/decls.vim
- autoload/go/asmfmt.vim
- autoload/go/complete.vim
- autoload/go/coverage.vim
- autoload/go/def.vim
- autoload/go/doc.vim
- autoload/go/fmt.vim
- autoload/go/guru.vim
- autoload/go/import.vim
- autoload/go/lint.vim
- autoload/go/package.vim
- autoload/go/path.vim
- autoload/go/play.vim
- autoload/go/rename.vim
- autoload/go/tags.vim
- autoload/go/test.vim
- autoload/go/textobj.vim
- autoload/go/tool.vim
- autoload/go/tool_test.vim
- autoload/go/util.vim
- doc/vim-go.txt
- plugin/go.vim
Fixes #1766; Fixes #1767
Using `-tags ''` is valid in pretty much all commands, but due to inconsistent ad-hoc application of shell escaping empty tags sometimes wouldn't get passed correctly.
The solution is to use `go#util#Exec()`, which handles this for us.
This will also fix issues with multiple build tags set (e.g. `let g:go_build_tags = 'aa bb'`).
> Fix shell escaping for :GoDoc, :GoDef

- scripts/bench-syntax
- scripts/run-vim
- scripts/runbench.vim
- test/parse.go
A script to benchmark the `syntax/go.vim` file. It's currently rather
slow if you enable all the `g:go_highlight` options even on modern
machines. This will allow us to easily do performance measurements.
> Add ./scripts/bench-syntax

- autoload/go/fmt.vim
This check was added two years ago in #735. I think it's safe to remove
now? It doesn't really do any harm, but does simplify things a bit.
Also happened to notice that `:GoFmtAutoSaveToggle` was broken:
Error detected while processing function go#fmt#ToggleFmtAutoSave:
line    7:
E118: Too many arguments for function: go#config#FmtAutosave
So fix that as well.
> Remove old goimports -srcdir workaround and fix :GoFmtAutoSaveToggle

- syntax/gohtmltmpl.vim
This change enable highlighting of `{{…}}` everywhere within html, for example in tags:
```html
<input type=checkbox {{ if .Check }}checked{{ end }} value="{{ .Value }}">
```
> Fix gohtmltmpl syntax to show everywhere

- plugin/go.vim
In appending item into the list, RHS must be a list.
> Fix go get flags for GoUpdateBinaries

- autoload/go/complete.vim
Return `true` instead of `true `.
Fixes #1817 and #1810
> fix gocode option string values

- plugin/go.vim
Hi,
I noticed that recently nsf/gocode is no longer maintained (please see [notice at the top of README](https://github.com/nsf/gocode#an-autocompletion-daemon-for-the-go-programming-language)). And now [mdempsky/gocode](https://github.com/mdempsky/gocode) is an official active repository of gocode.
So I think vim-go should use the new repository for now. This PR only changes the repository URL in vim-go repository.
Please note that it's not straightforward to change the URL because the new repo only supports Go 1.10+. What do you think, @fatih?
> gocode: Change repo from nsf/gocode to mdempsky/gocode

- autoload/go/debug.vim
Package name must come after subcommand (test/debug), dlv could not start when package name comes before subcommand
> Package name must come after subcommand

- autoload/go/test-fixtures/test/src/testcompilerror/testcompilerror_test.go
- autoload/go/test-fixtures/test/src/veterror/veterror.go
- autoload/go/test.vim
- autoload/go/test_test.vim
Handle vet errors (usually only have a filename and line number, with not column number available) as well as multi-line compiler errors.
Fixes #1802
> Handle test compilation errors

- autoload/go/guru.vim
In the k8s.io/kubernetes repo, vendor/k8s.io/{api,apiservers} etc. are
symbolic links to corresponding dir staging/src/k8s.io/{api,apiservers}.
vendor/k8s.io/apiserver -> ../../staging/src/k8s.io/apiserver
ImportPath detection for files under these staging directories will fail
because '%:p:h' does not match any items of 'go list'
For large projects like k8s, users tend to set the g:go_guru_scope
variable.  The change is mainly a workaround trying to improve
experience so that those not worked before will work now and it will not
affect existing usage.
> guru.vim: defer ImportPath check

- syntax/go.vim
By anchoring to the start of the document (since that's the only place
a package comment will appear), the number of false matches is greatly
reduced in some files.
Fixes #1747
> Improve performance of package comment regex

- autoload/go/textobj.vim
- doc/vim-go.txt
- ftplugin/go.vim
To select a comment block. Fixes #1508
Requires fatih/motion#4
> Add "ac" ("a comment") text object

- autoload/go/guru.vim
Output from a Neovim job may come in batches and splits on newlines.
When the output ends with a newline, the last element in the data passed
to the stdout and stderr callbacks will be the empty string. When it's
not the empty string, then last element is an incomplete line, and the
next call will contain the rest of the line in the first element of its
data.
Join shell arguments correctly when Neovim calls guru.
Fixes #1836
> fix guru output handling in Neovim

- autoload/go/complete.vim
- autoload/go/config.vim
- doc/vim-go.txt
- plugin/go.vim
nsf/gocode is not working well with Go 1.10. I just encountered it myself again. The author of original gocode also states and recommends the mdempsky/gocode fork over nsf/gocode: https://github.com/nsf/gocode#an-autocompletion-daemon-for-the-go-programming-language
We actually [moved once](https://github.com/fatih/vim-go/pull/1814), but because we didn't removed the obsolote settings, we weren't prepared for issues that were [reported](https://github.com/fatih/vim-go/issues/1817), and hence [reverted it back](https://github.com/fatih/vim-go/pull/1823)
This PR also removes all settings. The reason is that the new gocode doesn't support settings anymore. The author decided not the support it.
* For `autobuild`, this was removed because the author believe it's not
worth tackling it inside …
> gocode: switch to https://github.com/mdempsky/gocode

- autoload/go/debug.vim
- syntax/go.vim
Before, this was defined as part of the debug autoload, which would only
be invoked when a user started debugging for the first time. This caused
it to override any customizations a user may have had in their own
configuration.
By migrating the highlight groups to the syntax file, users can use
standard methods to override these colors if they don't work with their
chosen colorscheme, e.g. with a line like:
```vim
autocmd custom FileType go hi! GoDebugCurrent term=underline ctermbg=237 guibg=#3c3836
```
in their `vimrc`.
This supercedes fatih/vim-go#1840 and fixes fatih/vim-go#1839.
> Respect user debug highlight group customization

- autoload/go/util.vim
Commands such as :GoImports ended up calling "goimports" directly rather
than using the full path based on g:go_bin_path. Restore the previous
behavior of using the expanded binary path.
Fixes regression from #1771
(commit 32ae8640716530bd55062379177da51efb37dfd2,
"Fix infinite recursion when GOPATH is empty, part two").
___
Cc: @Carpetsmoker
I don't have `~/go/bin` in my `$PATH`, but I do have `let g:go_bin_path = expand('~/go/bin')` in my vimrc.
It would be nice to have a regression test for this, but `scripts/install-vim` always adds `$GOPATH/bin` to `PATH`, so I am not sure if it is feasible to do this?
> Fix wrong binary path for go#util#Exec

- autoload/ctrlp/decls.vim
If you run `GoDeclsDir ./some/package` with vim-go using CtrlP, it show the list of declarations in the package, but when you hit enter on one of them, it just opens a new buffer with the name of the file containing the selected symbol, but it doesn't correctly open the existing file. This fixes that issue.
> Fix GoDeclsDir for ctrlp on a directory other than '.'

- autoload/go/def.vim
PR #1866 was incomplete: `go#def#Jump()` calls `guru` asyncronously, and
not through `go#util#Exec()`, and so `:GoDef` fails if `guru` isn't
found in `$PATH`.
> Fix guru execution to use g:go_bin_path

- autoload/go/impl.vim
> impl: add support to complete packages

- autoload/go/def.vim
> def: only add build tags if it's present

- README.md
- doc/vim-go.txt
Two updates related to the minimum Vim version for this plugin:
* Added note in the [install](https://github.com/fatih/vim-go/blob/master/README.md#install) section of the README
* Added section in `/docs/vim-go.txt` for updating your default vim version
> Add minimum vim version requirement to README

- autoload/go/cmd.vim
> fix GoRun % in windows

- autoload/go/job.vim
- autoload/go/lint.vim
- autoload/go/lint_test.vim
- autoload/go/util.vim
* Run gometalinter asynchronously and vim-go's job api to to run it both Vim8 and Neovim.
* Correct a couple of documentation errors I came across during implementation.
> run gometalinter asynchronously in Neovim

- README.md
- doc/vim-go.txt
- plugin/go.vim
- scripts/install-vim
- scripts/runtest.vim
Put test output within its RUN and PASS/FAIL lines so that it's easier to identify which test is providing the output.
For instance, the  `Test_Vet` in `lint_test.vim` outputs `vim-go: [vet] FAIL`. Previously, this output would be output _after_ the test results:
```
=== RUN  Test_Vet
--- PASS Test_Vet (0.628221s)
vim-go: calling vet...
vim-go: [vet] FAIL
ok   lint_test.vim              2.651954s / 4 tests
```
But now, the output will be shown _within_ the test run:
```
=== RUN  Test_Vet
vim-go: calling vet...
vim-go: [vet] FAIL
--- PASS Test_Vet (0.618306s)
ok   lint_test.vim              2.598650s / 4 tests
```
> put test output within its RUN and PASS/FAIL lines

- autoload/go/test.vim
Support for running tests in a terminal in Neovim was accidentally dropped in #1864.
> restore nvim's support for running go test in a terminal

- CHANGELOG.md
Links without `https://` in GFM markdown will be rendered to error links like `https://github.com/fatih/vim-go/blob/master/github.com/fatih/vim-go/pull/1901`.
> fix CHANGELOG links

- autoload/go/complete.vim
- autoload/go/tool.vim
- ftplugin/go/commands.vim
- ftplugin/go/mappings.vim
- plugin/go.vim
Make sure :GoInfo echoes the info for the identifier under the cursor
when g:go_info_mode='gocode'.
Remove the auto argument from go#complete#Info; it is not needed. In
other locations, rename auto to echo so that it is clear what effect it
has instead of acting as a signal for _how_ it was called.
Fixes #1914.
> restore behavior of :GoInfo when g:go_info_mode='guru'

- plugin/go.vim
github.com/dominikh/go-tools/cmd/keyify -> honnef.co/go/tools/cmd/keyify
> Update package keyify's repository location

- autoload/go/config.vim
- autoload/go/mod.vim
- doc/vim-go.txt
- ftdetect/gofiletype.vim
- ftplugin/go/commands.vim
- ftplugin/gomod.vim
- ftplugin/gomod/commands.vim
- ftplugin/gomod/mappings.vim
- plugin/go.vim
- syntax/gomod.vim
This adds initial support for the `go.mod` file.  It adds the
followings:
* Syntax highligthing. We highlight keywords, strings, operator and
semver version. It works pretty well for now.
* Auto fmt on save. Command `:GoModFmt` or `Plug(go-mod-fmt)` for custom
mappings
Before we fully support the semantics of go.mod, I think this initially
will be helpful because I discovered that `go.mod` is read and edited a
lot. So going forward, this will make it easier experimenting with Go
modules.
related: #1906
> go.mod file support

- autoload/go/cmd.vim
`statustype` needs to be set in order to complete the statusline update
in job.vim
> cmd: fix status line updated upon completion

- autoload/go/complete.vim
- autoload/go/guru.vim
- autoload/go/tool.vim
- ftplugin/go/commands.vim
- plugin/go.vim
* Do not update the status line when guru commands are run via
autocommands.
* Update the status line when gocode is run via :GoInfo.
> Display statuslines consistently

- autoload/go/import.vim
> import: fix adding import to empty imports

- autoload/go/indent_test.vim
- indent/go.vim
Do not match the indentation of code that assigns a multi-line raw string within the raw string (i.e. the second line of a raw string should not match the indentation of the line of code that assigns the raw string to a variable).
Fixes #1800
> do not indent second line of raw string

- autoload/go/cmd.vim
- autoload/go/job.vim
* Echo errors when they cannot be parsed. Put the directory at the
beginning of the echoed messages to give context to the messages that
follow. The user may still need to call `:messages` to see the full list of errors....
* Remove redundant setting of statusline
Fixes #1942
> Fix async job errors

- ftdetect/gofiletype.vim
Comments are allowed in the go.mod file, so previously:
// Document stuff!
module foo/bar
require "other/pkg"
Would not get detected properly.
Also tweak regexp slightly: `module` must be followed by a space and at
least one character.
> Improve go.mod filetype detection

- autoload/go/complete_test.vim
- autoload/go/test-fixtures/complete/complete.go
Add a test for `go#complete#GetInfo`, because it has guarantees, and some users depend on it.
> add test for go#complete#GetInfo

- gosnippets/UltiSnips/go.snippets
- gosnippets/minisnip/_go_tt
- gosnippets/snippets/go.snip
The snippet only considers string input / output, and it needs to be modified for each test case, but it provides a clean, parallel testing compatible table testing boilerplate code.
Let me know if you have suggestions about tab stops or snippet name.
> snippet: Add table testing boilerplate snippet

- autoload/go/cmd.vim
- autoload/go/complete.vim
- autoload/go/coverage.vim
- autoload/go/def.vim
- autoload/go/guru.vim
- autoload/go/lint.vim
- autoload/go/rename.vim
- autoload/go/test.vim
- autoload/go/util.vim
Now that vim-go's async api support Neovim, go#util#has_job can handle
checking for Neovim instead of checking it inline.
> remove unneeded nvim checks

- autoload/go/lint.vim
Remove code that was redundant with vim-go's async job handling.
> simplify async gometalinter execution

- autoload/go/config.vim
- doc/vim-go.txt
Although this will make gocode slower by default, it provides the experience that most people expect. Reliability seems more important than performance... 🤔
> default gocode to propose from source

- .travis.yml
- Dockerfile
- autoload/go/test.vim
- autoload/go/test_test.vim
Update errorformat strings for go test for Go 1.11 test output while
maintaining compatibility with Go 1.10 test output, too. The changes
were validated locally by running the tests in vim-go-test containers
based on the respective versions of Go. I investigated trying to use the
json support, but it doesn't offer any real value for us yet. I may
revisit it later.
Update the go vet expecations; one of the strings changed.
Update to the Dockerfile base image and travis to use Go 1.11.
> support and test against Go 1.11

- plugin/go.vim
We're assuming for now to use the same binary name that also matches the
import path. But this is not always the case. To add support for an
experimental `gocode`, we need to install a second binary. This change
will allow us to do it by just adding a line, such as:
\ 'gocode-gomod':  ['github.com/stamblerre/gocode'],
This PR splits `go get` command into specific download and install
steps.
A follow up PR to add support for gocode-gomod will follow.
> go: install tools with their custom names

- plugin/go.vim
The binaries installed via `:GoUpdateBinaries` cannot be executable on Windows since the binaries do not have an extension.
This pull-request adds the ".exe" extension to the binary file name.
> Fix missing extension for Windows

- syntax/gomod.vim
Hi,
I started using Go modules with Go 1.11. And I found some highlights are not correct as follows:
- Version may have `+incompatible` suffix. I'm not sure that other words than 'incompatible' are used as suffix. For safety, I hard-coded `+incompatible` in the highlight definition.
- Comment after version is highlighted as part of version
I took screenshot of my `go.mod` before/after this fix.
- Before
- After
> Fix highlighting version on gomod

- autoload/go/util.vim
Fix shell related problems when `shellcmdflag` contains flags not understood by `/bin/sh` by resetting it to a safe value and restoring it at the end.
> preserve shellcmdflag and normalize for /bin/sh

- ftdetect/gofiletype.vim
Disable the highlight settings and syntax groups for other *.mod files.
The one downside of this is that a user that uses vim-go and also works in Module2, LambdaProlog, and Modsim III files will need to set the filetype for those other languages via _another_ autocmd. Is there really any vim-go user that also works one of those three other languages?
> disable other *.mod autocmds

- autoload/go/highlight_test.vim
- syntax/gomod.vim
* don't match +incompatible when major version is < 2.
* match pseudo versions correctly.
> match gomod versions correctly

- autoload/go/debug.vim
- autoload/go/job.vim
- doc/vim-go.txt
> add debugger support to Neovim
