fatih/vim-go

README.md

Thank you for working on this project, it has accelerated my learning and it is pretty fun having so much power in vim for go!

Goinfo typo

---

gosnippets/UltiSnips/go.snippets
gosnippets/snippets/go.snip

I've added a couple snippets I like to use for my own projects, such as a very useful one for a quick http test server and some test error handling.
Additionally, I added one for `a = append(a, b)`

Add a few snippets, mostly for testing

---

autoload/go/oracle.vim

Implementation proposal for a feature suggested in https://github.com/fatih/vim-go/issues/250#issuecomment-76425041

oracle: add full content of referring line

---

gosnippets/UltiSnips/go.snippets
gosnippets/snippets/go.snip

Added equals from https://github.com/benbjohnson/testing

snippets: add a convenient testing snippet

---

gosnippets/UltiSnips/go.snippets

Hi! 
I just added the handy ${VISUAL} configuration to UltiSnips snippets that was making sense to have it.
Regards,
LeoLuz

Add ${VISUAL} to UltiSnips snippets

---

autoload/go/cmd.vim
doc/vim-go.txt
ftplugin/go/commands.vim

Separate test command to run only the test immediate to your cursor.

Focused test command (go test -run 'Test...$')

---

syntax/go.vim

Highlight all Go operators

---

plugin/go.vim

Fixes #445
Relates issue: #434

go: add -f only for go version higher than 1.4.x

---

autoload/go/cmd.vim
doc/vim-go.txt
ftplugin/go/commands.vim

Hi, Fatih! First of all, great big thanks for your work on this excellent plugin. I have implemented simple go-generate support, by basically taking snippets of your code for go-build command. Hope that it will be useful.
Andrew.

Basic implementation of :GoGenerate command

---

plugin/go.vim

plugin/go: only load version if we call GoInstallBinaries

---

ftplugin/go/tagbar.vim

Before: ![Screenshot 1](http://i.imgur.com/9QXldk1.png)
After: ![Screenshot 2](http://i.imgur.com/0Ze2nj6.png)

Correct show import section in tagbar plugin.

---

autoload/go/oracle.vim

oracle: display an error if no code is selected

---

autoload/go/import.vim
ftplugin/go/commands.vim

Sometimes I want to add import with go-get.

:GoImport! to import with go get

---

autoload/go/fmt.vim

The current implementation of `gofmt -w` is incomplete as it cannot be
used from a BufWritePre hook. The command is run on a buffer's backing
file, but if the user's buffer has not been flushed to disk, gofmt
processes the existing file and we discard the user's changes.
We can avoid this situation by using a tempfile and moving the file into
place after a successful fmt.
Also note that `let &syntax = &syntax` is the preferred way of resetting
the syntax engine for a particular buffer.

Improve fmt-in-write by storing results in a tempfile

---

ftplugin/go/commands.vim

Fix `<Plug>(go-import)` mapping

---

autoload/go/oracle.vim

Hi @fatih,
This patch series removes a few bugs from the Oracle wrappers. Rationale is in the commit messages, and I am happy to provide further information.
Thanks!

Oracle fixes

---

autoload/go/gb.vim
ftplugin/go/commands.vim

Hi @fatih, 
I implemented gb test feature that refer to #420.  Please review it.
Thanks
win

gb: implement GbTest

---

README.md

I adjusted the spelling, grammar, and general flow of the README.md

Adjusted Spelling/Grammar of README.md

---

doc/vim-go.txt

Small changes in troubleshooting section.

Typo fixes in docs

---

autoload/go/cmd.vim

cmd: close quickfix window if successful

---

doc/vim-go.txt
syntax/go.vim

I setup the syntax with default on to match majority of other syntax files, let me know if I should invert.
Fixes #543

@spell for strings

---

syntax/gotexttmpl.vim

fix 558: fix goTplIdentifier regex so it doesn't go over limits

---

syntax/go.vim

The master list is at
https://github.com/golang/go/blob/master/src/go/build/syslist.go

syntax: Add support for all the values of GOARCH.

---

syntax/gotexttmpl.vim

Fix template variable highlighting

---

README.md

A small section of the readme with some suggestions around navigating through errors in Location Lists.

Update to mention Location lists navigation

---

autoload/go/cmd.vim
autoload/go/jobcontrol.vim
autoload/go/term.vim

cmd: fix not jumping when ! is passed for jobcontrol/term

---

autoload/go/def.vim

Signed-off-by: Koichi Shiraishi <zchee.io@gmail.com>

Support vimproc for godef

---

autoload/go/cmd.vim

I think I ran into a regression of #404 (where `:GoInstall` did not parse the paths in the output correctly.)
I fixed my issue locally with this PR by scavenging some logic from `go#cmd#Build`. However, I don't really know what I'm doing, so if there is a better way to fix this issue, let me know.
Thanks,

use make for GoInstall to correctly parse error paths

---

autoload/go/util.vim

util: disable forward slash

---

doc/vim-go.txt

As a new vim-go user, I love the comprehensive documentation provided. Here are a few suggestions that will hopefully make it even better.

docs: minor revisions to go-settings

---

autoload/go/def.vim

substitute all backslashes to slashes for filename.

---

autoload/go/fmt.vim

Remember fmt failure on a per-buffer basis

---

autoload/go/fmt.vim

fmt: save folds on close

---

autoload/go/fmt.vim

fallback for mkview

---

autoload/go/fmt.vim

Put mkview/loadview changes behind go_fmt_experimental

---

autoload/go/cmd.vim

Fixes regression introduced in #700, as documented on #739 and #743.

show output of :GoRun

---

autoload/go/def.vim
autoload/go/doc.vim
autoload/go/import.vim

Prevents nasty side effects from user mappings

Use mapping independent `normal!`

---

syntax/go.vim

syntax highlighting for //go:generate

---

syntax/gotexttmpl.vim

syntax: Fix gotexttmpl identifier highlighting

---

autoload/go/term.vim

term: close location list if cmd's result is successful

---

autoload/go/coverage.vim
autoload/go/jobcontrol.vim
autoload/go/term.vim

coverage: fix not working if go_term_enabled is set

---

autoload/go/asmfmt.vim
autoload/go/coverage.vim
autoload/go/lint.vim

exit code should be checked with 0

---

autoload/go/def.vim

`function! go#def#Jump` should pass tags flags to guru.

pass -tags flag to guru

---

autoload/go/coverage.vim

coverage: fix for cases of syntax=off

---

ftplugin/gohtmltmpl.vim

ftplugin: add gohtmltmpl.vim

---

gosnippets/UltiSnips/go.snippets
gosnippets/snippets/go.snip

Updated `benchmark` snippet to use for loop

---

gosnippets/UltiSnips/go.snippets
gosnippets/snippets/go.snip

Added http to http handler snippet

---

autoload/go/complete.vim
doc/vim-go.txt

This will hopefully make it more easier to use completion for newcomers.
It's totally optional and can be disabled if wished.
Closes #815

complete: enable autobuild and propose-builtins

---

ftplugin/go/mappings.vim

Hi, 
In this PR I have added mapping for GoImports, to make GoImports assignable to any key combination.

Added GoImports mapping

---

autoload/go/cmd.vim

cmd: do not create test binary artifact for :GoTestCompile

---

autoload/go/def.vim
doc/vim-go.txt
plugin/go.vim

def: add go_def_mode setting, we now support godef too

---

autoload/go/doc.vim

open GodocView if argument is provided for :GoDoc

---

autoload/go/fmt.vim

fmt: fix goimports picking up -srcdir

---

autoload/go/doc.vim

Fixed typo causing GoDocBrowser to fail

---

gosnippets/UltiSnips/go.snippets
gosnippets/snippets/go.snip

Unsure if there is more to it than this,  but make yaml tag completion work as json does.

add yaml tags completion

---

autoload/go/guru.vim

Neovim supports JSON, :GoSameIds now works.

---

autoload/go/guru.vim
doc/vim-go.txt
ftplugin/go/commands.vim
ftplugin/go/mappings.vim

Hi,
Alan Donovan at Gophercon 2016 showed that `guru whicherrs` is a thing, which I noticed was missing from vim-go. This is my attempt at adding it.
Cheers,
KH

guru: add :GoWhicherrs

---

autoload/go/fmt.vim

So after updating I found this issue where when I saved I would get an error of:
`setfperm` unknown function. This PR should fix that issue.
Thanks @fatih for letting me fix this. :D

Fixes the 'setfperm' issue

---

autoload/go/fmt.vim

fmt: pass full name to -srcdir for upcoming new features

---

autoload/go/guru.vim
doc/vim-go.txt
ftplugin/go/commands.vim
ftplugin/go/mappings.vim

Add two new commands to make it easier. I'm still not finished with ideas. But it's a start. Contains #943 as well (with the merge conflicts solved). Thanks @idawes

Improve :GoSameIds

---

syntax/go.vim

fixed goField regexp

---

autoload/go/complete.vim
doc/vim-go.txt

complete: add g:go_gocode_socket_type setting

---

syntax/go.vim

@fatih 
Sorry,
https://github.com/fatih/vim-go/pull/1030 has a bug.
Please, merge this pr 🙇 
thanks.

Fix bug in syntax highlighting

---

autoload/go/def.vim

def: do not open a split for modified file

---

autoload/ctrlp/decls.vim
autoload/go/alternate.vim
autoload/go/asmfmt.vim
autoload/go/cmd.vim
autoload/go/complete.vim
autoload/go/coverage.vim
autoload/go/def.vim
autoload/go/doc.vim
autoload/go/fmt.vim
autoload/go/guru.vim
autoload/go/impl.vim
autoload/go/import.vim
autoload/go/jobcontrol.vim
autoload/go/lint.vim
autoload/go/list.vim
autoload/go/package.vim
autoload/go/path.vim
autoload/go/play.vim
autoload/go/rename.vim
autoload/go/template.vim
autoload/go/term.vim
autoload/go/textobj.vim
autoload/go/tool.vim
autoload/go/ui.vim
autoload/go/util.vim

Used `vint` to go over the codebase and applied the (easy to do)
suggestion of adding `abort` to every autoload function.

Add abort to every autoload function

---

CHANGELOG.md
autoload/go/cmd.vim
autoload/go/coverage.vim
autoload/go/def.vim
autoload/go/doc.vim
autoload/go/guru.vim
autoload/go/job.vim
autoload/go/jobcontrol.vim
autoload/go/lint.vim
autoload/go/rename.vim
autoload/go/statusline.vim
autoload/go/util.vim
doc/vim-go.txt
ftplugin/go.vim
ftplugin/go/commands.vim
ftplugin/go/mappings.vim
plugin/go.vim
syntax/go.vim

Add vim-8.0 support

---

autoload/go/doc.vim
autoload/go/guru.vim

go: do not use new type variables

---

autoload/go/cmd.vim

cmd: fix :GoTestFunc for job API

---

autoload/go/cmd.vim

cmd: wall tries to write to unnamed buffer, neglect errors

---

CHANGELOG.md
autoload/go/tool.vim
doc/vim-go.txt
ftplugin/go/commands.vim
ftplugin/go/mappings.vim
plugin/go.vim

info: add option to change underlying tool for :GoInfo

---

doc/vim-go.txt
ftplugin/go/mappings.vim

Add plug mapping for golint
Fixes #1068

lint: add (go-lint) plug mapping

---

autoload/go/path.vim

path: use echom so it's showed when used completion

---

autoload/go/cmd.vim

cmd: do not expand coverage arguments

---

autoload/go/coverage.vim

Just removing the matches is enough for us.
Fixes #1034

coverage: no need to change turn on/off syntax

---

autoload/go/asmfmt.vim
doc/vim-go.txt
plugin/go.vim

Change default value of `g:go_asmfmt_autosave` to 0.

---

syntax/go.vim

These were indeed annoying. Let us turn them off
closes #1163

syntax: switch options to off

---

doc/vim-go.txt

docs: fix unused feature

---

autoload/go/cmd.vim

cmd: we don't need to shellescape for jobs

---

autoload/go/lint.vim

To config gometalinter --exclude option

Add go_metalinter_excludes config variable

---

autoload/go/term.vim

term: fix cwd after running command

---

autoload/go/lint.vim

Fixes https://github.com/fatih/vim-go/pull/1297

Specifies the type of list to use in GoMetaLinter, by go_list_type

---

autoload/go/test.vim

test.vim: fix messages with colons

---

autoload/go/coverage.vim

I dont know if it has been running when I execute GoCoverageToggle, so add some echo message like GoTest.

add echo message for GoCoverageToggle

---

autoload/go/path.vim

path: fix gobin path for go => 1.7

---

autoload/go/path.vim

path: fix autp detecting of GOPATH for import paths with string 'src'

---

.github/CONTRIBUTING.md

There was a missing `)` character.

Fix link in CONTRIBUTING.md

---

autoload/go/lint.vim
doc/vim-go.txt

Instead of the current working directory.
Fixes #1375

Run :GoLint against the package of the open file

---

autoload/go/fmt.vim

fmt.vim: only close quickfix if its belongs to gofmt

---

doc/vim-go.txt

Asked for in https://github.com/fatih/vim-go/pull/1419

Add FAQ entry for how to run focused ginkgo tests

---

README.md
doc/vim-go.txt

I've been planning on this for a while: proofread all the documentation and
improve where required.
This changes some of the wording to sound better in my opinion. It also adds
various tags where it makes sense, removes or merges some things, and adds a few
minor things.
I'll split it up in several PRs because doing all the documentation in one go is
a lot of work.

Proof read documentation: "Intro", "Install", and README

---

CHANGELOG.md

:%s,\(#\d\+\),[\1](https://github.com/fatih/vim-go/pull/\1),

Fix ChangeLog links

---

.github/ISSUE_TEMPLATE.md

This gives us GOPATH and such, as well as OS info. Also word things
stronger that people *must* fill this out.

Ask for "go env"

---

autoload/unite/sources/decls.vim

or this will make Unite run err the first time

comment out err modeline

---

.travis.yml
.vintrc.yaml
Dockerfile
autoload/ctrlp/decls.vim
autoload/fzf/decls.vim
autoload/go/cmd.vim
autoload/go/coverage.vim
autoload/go/fmt.vim
autoload/go/guru.vim
autoload/go/list.vim
autoload/go/tags.vim
autoload/go/test.vim
autoload/gotest.vim
compiler/go.vim
ftdetect/gofiletype.vim
scripts/install-vim
scripts/lint
scripts/runtest.vim
syntax/gohtmltmpl.vim

https://github.com/syngan/vim-vimlint
https://github.com/Kuniwak/vint
Also fix some errors. I disabled checks for all errors that would result in a large number of changes or non-trivial changes. We can do that later when we have better tests.

Add some VimScript lint tools

---

autoload/go/debug.vim

Fixes: #1693
It wouldn't set the command to `continue` if the `next` command was used
to start the program.

More reliable way to keep track if the program is running

---

.codecov.yml

* do not post comments to pull requests
* only report coverage for files in autoload/go
* ignore coverage of test files.
* allow checks to pass with up to 1% reduction in code coverage.

Add codecov.io configuration

---

autoload/go/complete.vim
autoload/go/util.vim

Check that the "env" key is supported in job_start

---

autoload/go/debug.vim

Fix :GoDebugStart

---

doc/vim-go.txt

Update the answer about performance now that we have a better
understanding about what caused some of the problems prior to v1.17.

update performance FAQ

---

autoload/go/debug.vim

Fix missing debugger package parameter

---

autoload/go/complete.vim
autoload/go/config.vim
doc/vim-go.txt
plugin/go.vim

Revert "gocode: switch to https://github.com/mdempsky/gocode"

---

autoload/go/cmd.vim
autoload/go/tool.vim

Add build tag support to :GoDeps, :GoDoc, :GoRun, and :GoFiles.
Fixes #1857

add more build tag support

---

.travis.yml

Until https://github.com/Kuniwak/vint/issues/287 is fixed

travis: fix temporary vint issue

---

autoload/go/impl.vim

fix small typo

---

README.md

Vundle (https://github.com/VundleVim/Vundle.vim) is one of the most popular methods to install packages in vim; installation method added.

Vundle installation method added

---

syntax/go.vim

Include context.Context to goExtraType highlight group.

Highlight context.Context

---

autoload/go/complete.vim

return an identifier description from go#complete#GetInfo

---

autoload/go/def.vim

def: make sure to make the declaration's window active

---

ftplugin/go/mappings.vim

Pass a value for the showstatus argument to go#tool#Info and
go#guru#SameIds in the go-info and go-sameids mappings.

fix mappings for go-info and go-sameids

---

autoload/go/list.vim

add GoModFmt list type

---

autoload/go/job.vim

Hide nagging message when there is nothing to report

---

autoload/go/job.vim

set the job directory correctly

---

CHANGELOG.md
autoload/go/mod.vim

check for >= go1.11 correctly

---

autoload/go/debug.vim

debug: exit busy wait when dlv exits

---

autoload/go/config.vim

add getter for g:go_echo_go_info

---

autoload/go/job.vim

Fix the handling of Neovim channel output, especially for raw mode.

fix neovim channel output handling

---

autoload/go/auto.vim
autoload/go/config.vim

respect g:go_jump_to_error when g:go_metalinter_autosave is set

---

autoload/go/lsp.vim

Use the usual lsp handler functionality for handling the response to an
initialize request.
Please enter the commit message for your changes. Lines starting

use lsp handlers for initialize result

---

autoload/go/lsp.vim

completion: handle errors gracefully

---

autoload/go/path.vim
autoload/go/uri.vim

encode windows file uri correctly

---

autoload/go/issue.vim

fix typo in go#issue#New

---

autoload/go/job.vim
autoload/go/lint.vim
autoload/go/test.vim
autoload/go/test_test.vim

do not change to list window when bang is set

---

autoload/go/tags.vim
autoload/go/tags_test.vim
autoload/go/test-fixtures/tags/add_all_golden_options.go

tags: support tag options on initial add

---

doc/vim-go.txt

update patreon links to bhcleek's page

---

autoload/go/doc.vim

doc: set method anchor correctly

---

autoload/go/mod.vim
autoload/go/package.vim

I'm using Go tip and got error.
(Also fixes another error when return empty lines from format)

Fix errors

---

plugin/go.vim
scripts/install-vim

Update the install script to install Neovim v0.3.2 instead of the latest
nightly.

update install script to install Neovim v0.3.2

---

autoload/go/debug.vim

debug: pass is_test to go#debug#Start when restarting

---

autoload/go/test.vim

fixes https://github.com/fatih/vim-go/issues/2396
tested and working.

fix test terminal handling

---

autoload/go/auto.vim

autocmd: don't format when saving to a different file

---

autoload/go/doc.vim

I think this patch is better about judgement of can use or not use popup window.

Update popup window's judgement

---

.travis.yml
autoload/go/config_test.vim
autoload/go/lsp.vim
scripts/runtest.vim

Actually remove missing directories.

lsp: fix CleanWorkspaces

---

autoload/go/guru.vim
autoload/go/lsp.vim
autoload/go/lsp/message.vim

sameids: use gopls instead of guru to find same ids

---

autoload/go/lsp/message.vim

lsp: use correct values for boolean json encoding

---

autoload/go/highlight_test.vim

Add a test for 0 as a slice index.
Add a test for 0 as a slice element.

syntax: add tests for 0 numeric literals

---

autoload/go/lsp/message.vim

lsp: use g:go_gopls_use_placeholders to register for snippets

---

gosnippets/UltiSnips/go.snippets

Add snippets for error wrapping, select, case, type switches, and
debugging print statements.

snippets: add some snippets from #2455

---

autoload/go/lint.vim

Update code quality tools' progress messages when commands fail.
Fixes #2645

lint: update progress with failure messages

---

doc/vim-go.txt

small documentation typo fix

---

autoload/go/lsp.vim

Handle some null arrays to avoid errors.
Fixes #2701

lsp: handle some null arrays

---

autoload/go/config.vim
autoload/go/lint.vim
doc/vim-go.txt

This as it originally was, rebased onto and with conflicts resolved from master.

#2655 continued

---

autoload/go/lsp.vim

Preserve the order of messages in the log; using a timer is fine
generally, but can introduce ordering problems when multiple timers are
scheduled to fire at nearly simultaneously. Therefore, provide a queue
of messages and only start a timer when the queue is empty.

lsp: preserve the order of messages in the log

---

autoload/go/def.vim

def: fix the filename passed to gopls on Windows

---

autoload/go/lsp.vim

lsp: handle null and empty lists in infoDefinitionHandler

---

autoload/go/uri.vim
autoload/go/uri_test.vim

lsp: handle encoding and decoding of multi-byte characters in paths

---

autoload/go/cmd.vim

cmd: show command in :GoRun when g:go_debug includes shell-commands

---

autoload/go/lsp.vim

Send synchronization messages even when files don't exist as long as the
file directory exists.

lsp: send sync messages when files don't exist

---

autoload/go/cmd.vim

run: transform file arguments to absolute paths

---

autoload/go/config.vim
autoload/go/lsp/message.vim
doc/vim-go.txt

add an option to control gopls' analyses config

---

.github/workflows/test.yml
.travis.yml
README.md
scripts/test

Add a GitHub Actions workflow to test and lint vim-go. So far this is a
straight port of the Travis CI configuration.
Closes #2788

add github action to test and lint

---

doc/vim-go.txt

Update the documentation for terminal options for clarity and accuracy.

doc: update terminal options documentation

---

README.md
doc/vim-go.txt
scripts/install-vim

It's not the latest release, but it's relatively recent and certainly
much better than v0.3.2

test against Neovim v0.4.0

---

CHANGELOG.md

Fix link in recent changelog entry

---

doc/vim-go.txt

doc: clarify how g:go_fmt_autosave and g:go_imports_autosave behave

---

autoload/go/util.vim

highlight: handle exceptions when trying to add properties

---

autoload/go/auto.vim
autoload/go/lsp.vim

completion: do not show documentation at command-line

---

autoload/go/debug.vim

Do not block while waiting on responses from delve so that users can
continue to interact Vim.
Fixes #2915

debug: non blocking messages in Vim

---

autoload/go/lsp.vim

lsp: ignore nulls in definition and type definition handlers

---

autoload/go/debug.vim

debug: warn when file is written after starting debugger

---

autoload/go/lsp.vim

lsp: return current diagnostics when file is unchanged

---

doc/vim-go.txt

doc: fix references to g:go_imports_mode

---

autoload/go/tool.vim

info: remove reference to gocode in error message

---

autoload/go/debug.vim
doc/vim-go.txt

debug: add halt command

---

autoload/go/lsp.vim
autoload/go/test-fixtures/fmt/src/imports/goimports.go

lsp: insert solitary empty lines when applying text edits

---

autoload/go/highlight_test.vim
scripts/runtest.vim

This reverts commit 92195505a0577a57713bc4c2ac8e84eeb141fc28.

Revert "test: disable highlight tests"

---

autoload/go/job.vim
autoload/go/lint.vim
autoload/go/lint_test.vim
scripts/run-vim

This is a small set of improvements that were made during the course of implementing another branch. They're in a separate PR to avoid cluttering an upcoming PR.
Copy the list being extended in a test so that the list being extended
isn't modified by extend().

small tweaks

---

autoload/go/cmd.vim

cmd: fix call to go#util#Chdir

---

doc/vim-go.txt

Please review the doc changes and accept the PR.

Doc fix for g:go_debug_mappings example.Bug #3099

---

ftdetect/gofiletype.vim
syntax/gosum.vim

add syntax highlighting for go.sum files

---

autoload/go/fillstruct_test.vim

Adjust the test expectations for the gopls implementation for
fillstruct.

fillstruct: adjust expectations for gopls

---

autoload/go/debug.vim

debug: display map and slice variables better

---

doc/vim-go.txt
ftplugin/go/commands.vim
ftplugin/go/mappings.vim

mappings: add go-fmt

---

autoload/go/debug.vim

Signed-off-by: Eric Lagergren <elagergren@spideroak-inc.com>

debug: add Delve register support

---

plugin/go.vim

Install latest releases of tools when possible instead of their latest
master branch.

plugin: install latest releases of tools

---

autoload/go/lsp.vim

lsp: hookup noop sendMessage when gopls is missing

---

README.md

Plugin is compatible with neovim but installation instructions are slightly different

Neovim packages instructions

---

syntax/go.vim

syntax: improve goOctalError highlight group

---

.github/workflows/test.yml

Test with Go 1.17 and stop testing with Go 1.15.

test with Go 1.17

---

autoload/go/lint.vim
autoload/go/tool.vim
autoload/go/util.vim

lint: allow /... in :GoDiagnostic package arguments

---

syntax/go.vim

Fixes a small regression from #3308

syntax: highlight named import lines

---

autoload/go/lsp.vim
autoload/go/util.vim

lsp: do not add directories in the module cache to the workspace

---

autoload/go/auto.vim
autoload/go/issue.vim
autoload/go/template.vim
ftplugin/go.vim
plugin/go.vim

plugin: resolve symlinks before calling DidOpen

---

syntax/gohtmltmpl.vim

Revert "Set `b:main_syntax`, not `g:`"

---

ftdetect/gofiletype.vim
syntax/gowork.vim

syntax: add syntax for go.work files

---

autoload/go/job.vim

Refactor Neovim channel callbacks so that callbacks executed in response
to channel data can cause more data to come in on the channel and be
handled without blocking the handling of the subsequent data.
Fixes #3385

job: refactor Neovim channel callbacks

---

autoload/go/lsp.vim
autoload/go/lsp/filechangetype.vim
autoload/go/lsp/message.vim
autoload/go/util.vim
doc/vim-go.txt
ftplugin/go/commands.vim
ftplugin/gomod.vim

add :GoModReload

---

autoload/go/debug.vim

debug: fix connect address argument check

---

autoload/go/lsp.vim

tool: display LSP diagnostics in hover balloon

---

doc/vim-go.txt

Add a mention about displaying diagnostics, too.

doc: update go#tool#DescribeBalloon() documentation

---

autoload/go/util.vim

util: handle joining args when shell is powershell

---

doc/vim-go.txt

Describe installing a specific version of a binary.

doc: update :GoUpdateBinaries and :GoInstallBinaries documentation

---

autoload/go/coverage.vim
doc/vim-go.txt
ftplugin/go/commands.vim

Add :GoCoverageOverlay command.
Closes #3467

coverage: add GoCoverageOverlay

---

autoload/go/doc.vim

Execute go doc in the expected working directory so that following a doc chain works even when the working directory regardless of what the working directory was at the first invocation of getting documentation in the chain.

doc: execute go doc in expected working directory

---

autoload/go/def.vim
ftplugin/go.vim
scripts/install-vim

def: use the native tag stack when possible

---

syntax/go.vim

Add support for the functions that Go 1.21 added to the language specification: clear, min, and max.

syntax: add new builtins

---

autoload/go/lsp.vim

sameids: fix highlighting preceded by multibyte characters

---

autoload/go/lsp.vim

lsp: check state after checking debug mode

---

autoload/go/complete.vim

Fix off by one in column calculation introduced in #3617.
Fixes #3625

complete: fix off by one

---

plugin/go.vim

This reverts commit befe5ba8c4c3fa57cc09ea2adcd28343cc73c931.

plugin: install latest revive

---

gosnippets/UltiSnips/go.snippets
gosnippets/snippets/go.snip

Add `fuzz` snippet for [fuzzing](https://pkg.go.dev/testing#hdr-Fuzzing) tests.
```go
func FuzzXYZ(f *testing.F) {
f.Fuzz(func(t *testing.T, ...) {
...
})
}
```

snippets: add fuzz function

---

autoload/go/lint_test.vim

Add test in module-aware mode and DRY the lint tests.

lint: add test in module-aware mode

---

autoload/go/doc.vim

doc: add double border around popup window
